### ISSUE TITLE
support copying bundles referenced by other bundles in images lock

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#10]
we currently do not allow to reference a bundle as an image inside a bundle. example where this might be helpful is: "we have a bundle that delivers configuration that references bunch of other bundles to be installed later".

gotta make sure that we dedup the tree since there could be cycles.

**Comment by timothysc** [comment]
Yup, definitely want!

**Comment by aaronshurley** [comment]
Proposal: https://github.com/k14s/design-docs/pull/3
Markdown formatted view: https://hackmd.io/b9pHX-S9QXaQ8je1Y8G6XA?view

**Comment by aaronshurley** [comment]
This work has been completed and released as a part of [v0.6.0](https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.6.0).
