### ISSUE TITLE
Document support for HTTP proxies

### ISSUE THREAD

**Issue by pivotaljohn** [carvel-dev/imgpkg#108]
**Describe the problem/challenge you have**
I wanted to know whether `imgpkg` supported proxies. But the documentation is silent on the subject.

**Describe the solution you'd like**
A (small) section describing how to configure that (or point to clear step-by-step instructions on how to do so).

**Anything else you would like to add:**
This was answered in a Slack message: https://kubernetes.slack.com/archives/CH8KCCKA5/p1616100380046600

**Comment by aaronshurley** [comment]
This makes sense to add. Moving this to the Unprioritized Backlog for now so that we can group it with other documentation improvements. Contributions are welcome :)
