### ISSUE TITLE
rename copy's --include-non-distributable to --include-non-distributable-layers

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#112]
better naming for the flag. this is a breaking change but we are pretty early with this functionality.

- [x] update docs on the website

**Comment by aaronshurley** [comment]
@DennisDenuto @joaopapereira @pivotaljohn any thoughts on this flag rename?

If we move this to `carvel-accepted` then we could likely prioritize it sooner than later since this feature hasn't been available for too long.

**Comment by DennisDenuto** [comment]
It is a slightly better name than what we have. Engineering wise, assuming we are not concerned with backwards compatibility, it is a *really* cheap change to make. 

If we are concerned with backwards compatibility, we could keep a 'hidden' flag with the old name (`--include-non-distributable`)

**Comment by joaopapereira** [comment]
I like the improvement, going to accept the story.
In my point of view, I think we should keep the old flag, but hide it. We can provide the following message (in STDERR) if the user includes the old flag:
`The flag "--include-non-distributable" is deprecated and will be removed in the near future. Please use the flag "--include-non-distributable-layers" instead.`

**Comment by cppforlife** [comment]
my 2c: especially for less commonly used flags it's ok _for now_ to have a bit of breaking functionality since we are pre v1.

**Comment by joaopapereira** [comment]
After talking with the requester of the feature I think it is ok to just do the breaking change.
So changing the recommendation to rename the flag.

Since this is a small change I believe we can skip the acceptance criteria. Accepting the story

**Comment by joaopapereira** [comment]
@aaronshurley we should prioritize this story since we are planning in doing a breaking change

**Comment by joaopapereira** [comment]
Implemented in version v0.7.0
