### ISSUE TITLE
confusing error message when directory is not a bundle directory

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#115]
```
$ imgpkg push -b k14stest/dk-test-repo-bundle -f examples/packaging-demo/repo
Error: Expected one '.imgpkg' dir, got 0:
```

seems like we can improve error message to indicate that this directory is not a bundle and needs to have a .imgpkg if it wants to be one. also what's up with trailing `:`?

**Comment by gcheadle-vmware** [comment]
Agreed. This error message should be improved, I was able recreate this issue by running from the imgpkg repo root dir:
```
imgpkg push -b k14stest/gc-test-repo-bundle -f examples/basic-step-1
Error: Expected one '.imgpkg' dir, got 0:
``` 

When adding an `.imgpkg` dir with no `imagesLock` file to the basic-step-1 dir, and then running the same command, I get: 
```
mkdir examples/basic-step-1/.imgpkg
imgpkg push -b k14stest/gc-test-repo-bundle -f examples/basic-step-1
Error: Reading path /Users/garrettcheadle/dev/imgpkg/examples/basic-step-1/.imgpkg/images.yml: 
open /Users/garrettcheadle/dev/imgpkg/examples/basic-step-1/.imgpkg/images.yml: no such file or directory
```
I think this error is better, but I feel the message should also include explicit information about bundles requiring an 
`.imgpkg/images.yml` file.

**Comment by carlisia** [comment]
👋 I'm going to take a stab at this.

**Comment by joaopapereira** [comment]
let us know if you need any help 😄

**Comment by carlisia** [comment]
Just a qq: I noticed at least some of those test could be in a table test structure. Is it ok to do that or you are trying to avoid it for these tests?

**Comment by carlisia** [comment]
*some of the tests in the `push_test.go`, which is where I'm adding cases to test the validation logic I'm adding.

**Comment by joaopapereira** [comment]
We have been trying to move our tests into a `t.Run` style, like https://github.com/vmware-tanzu/carvel-imgpkg/blob/develop/pkg/imgpkg/bundle/bundle_images_lock_test.go, and replace manual `t.Fatalf` with `testify` assertion framework.
I think we are ok with a table test format in general, just let's make sure we gain readability in these tests 😃
