### ISSUE TITLE
Use VerifyReadCloser for tar images

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/imgpkg#12]
Using [ggcr's verify closer](https://github.com/google/go-containerregistry/blob/6344e5703ce06861d6acdf6601c04fce64f4bbaf/pkg/v1/v1util/verify.go#L47) allows us to ensure the bits we read match the expected hash

**Comment by cppforlife** [comment]
done in kbld: https://github.com/k14s/kbld/commit/f6538ce54ba6c7ad0f849878031d5ec084c20857

**Comment by cppforlife** [comment]
done in imgpkg: https://github.com/vmware-tanzu/carvel-imgpkg/commit/eea38649ed2cdb76ea36b881acffdf902e0ebc26
