### ISSUE TITLE
Copying from a tarfile fails if the image doesn't exist in the registry anymore

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/imgpkg#127]
**What steps did you take:**
1. Create a bundle that references img1
2. Copy the bundle to a tarfile
2. delete img1 from  Registry A
3. copy from the tarfile to Registry A

**What happened:**
```
copy | importing 5 images...
copy | importing gcr.io/kubebuilder/kube-rbac-proxy@sha256:a06e7b56c5e1e63b87abb417344f59bf4a8e53695b8463121537c3854c5fda82 -> registry.local:5000/opinions/bundle-relocated@sha256:a06e7b56c5e1e63b87abb417344f59bf4a8e53695b8463121537c3854c5fda82...
copy | imported 0 images
Error: Getting mountable image failed: registry.local:5000/opinions/samples/opinion-server@sha256:e5892efcc2ffa9ca3ab27966300f66b63ba481e186487adfa71c5b9d425e20a8: GET http://registry.local:5000/v2/opinions/samples/opinion-server/manifests/sha256:e5892efcc2ffa9ca3ab27966300f66b63ba481e186487adfa71c5b9d425e20a8: MANIFEST_UNKNOWN: manifest unknown; map[Name:opinions/samples/opinion-server Revision:sha256:e5892efcc2ffa9ca3ab27966300f66b63ba481e186487adfa71c5b9d425e20a8]
```
**What did you expect:**
Copy to succeed

**Anything else you would like to add:**
imgpkg copy is trying to create a mountable object by querying the registry. Either change it to only copy the image from the tarfile, or if querying for an image to get a mountable object fails, fallback to copying from the tarfile

**Environment:**

- imgpkg version (use `imgpkg --version`): v0.6.0
- Docker registry used (e.g. `Docker HUB`):  
- OS (e.g. from `/etc/os-release`): osx

**Comment by cppforlife** [comment]
> if querying for an image to get a mountable object fails, fallback to copying from the tarfile

i think it would great if we can avoid making a network request from an air-gapped environment to external registry.

**Comment by DennisDenuto** [comment]
> i think it would great if we can avoid making a network request from an air-gapped environment to external registry.

The fix in PR https://github.com/vmware-tanzu/carvel-imgpkg/pull/128 will *only* make a network request `Get` image Manifest *if* the source and destination registry url's match.

We are making the assumption that in an airgapped environment, practically speaking the registry URL's will be different. 

Technically however, it is possible that a public registry and an airgapped registry share the same registry URL.

In which case, the change introduced in the PR, will fail to `Get` an image Manifest, and fall back to uploading the images from the tarball instead.

**Comment by DennisDenuto** [comment]
Fixed as part of https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.6.1
