### ISSUE TITLE
align with manifest bundle KEP

### ISSUE THREAD

**Issue by jdef** [carvel-dev/imgpkg#13]
I wasn't sure where else to post this, but it looks like something similar is cooking up in this KEP: https://github.com/kubernetes/enhancements/pull/1481/files

**Comment by ewrenn8** [comment]
Thanks for the heads up! We will keep an eye on this.

**Comment by stealthybox** [comment]
Heads up that we merged the KEP.
There's interest in getting this to work with kubebuilder-declarative-pattern and kops as next steps.

**Comment by danielhelfand** [comment]
As an update here, seems like there is an ongoing discussion from @cppforlife with regard to the KEP and whether the KEP could be amended to [change the metadata directory into a hidden directory](https://github.com/kubernetes/enhancements/pull/1481#issuecomment-741889970).

**Comment by danielhelfand** [comment]
@cppforlife Any follow up that can be done on your comment [here](https://github.com/kubernetes/enhancements/pull/1481#issuecomment-742563673) to potentially amend the KEP?

**Comment by cppforlife** [comment]
@danielhelfand bumped the thread there. ultimately we are compatible with that format since folks can just include metadata directory if they need to.

**Comment by danielhelfand** [comment]
Going to close this then. But please feel free to repoen if there is anything more to be done.
