### ISSUE TITLE
Improve debugging failures

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/imgpkg#130]
### Acceptance Criteria:
Provide debugging feature to imgpkg to expose ggcr logs.
#### Scenario 1: Debug flag is listed in docs and help text
**As an** imgpkg user looking for information about debugging
**I want** to see information explaining the debug flag in both the docs and help text
**So that** I know to expect logs providing visibility between imgpkg and a registry, if debug is toggled on.
#### Scenario 2: Debug an error from imgpkg command
**As an** imgpkg user wanting to debug an error, when I run my command with the ` --debug` flag,
**I want** imgpkg to print logs from its communication with registries
**So that** I will be able to deduce if the root cause of the error is imgpkg, or the information provided to the registries. 

*Notes:*
- see examples later in this comment.
---

**Describe the problem/challenge you have**

Due to the strong relationship between imgpkg has with registries, and that certain behavior in registries vary depending on the registry provider, when an error is presented to the user it is currently difficult to debug the root cause.

It is difficult to debug because:
a) The error returned to the user is too generic to provide a concrete reason for the failure. i.e. Calling `HEAD` on harbor can return a `401` to indicate that the image cannot be found, or it can be indicative of an `auth` related error
b) There can be various paths to the same error, and without having visibility between imgpkg and a registry, it is hard to determine root causes.

**Describe the solution you'd like**
a `--debug` or `IMGPKG_DEBUG` env variable that exposes *at least* the ggcr log output to gain visibility of the requests between imgpkg and the registry in question.

**Anything else you would like to add:**
- The `ggcr` library provides a registry option to set such logging. https://github.com/vmware-tanzu/carvel-imgpkg/blob/0492637dd358d7eae4a92a2a3c6d31286b5e0833/vendor/github.com/google/go-containerregistry/pkg/registry/registry.go#L95

- We have had to in the past compile a version of imgpkg that enabled such logging to help troubleshoot.
- Ensure that sensitive information is redacted

---
Example:
- [#carvel@2021-06-02T15:12Z](https://kubernetes.slack.com/archives/CH8KCCKA5/p1622646773264100) — 13 minute timeout before any output.
- [#carvel@2021-06-03T16:28Z](https://kubernetes.slack.com/archives/CH8KCCKA5/p1622737728282300) — authentication failed, triggering progress bar failure because channel was closed
  - the progress bar bug is fixed with https://github.com/vmware-tanzu/carvel-imgpkg/pull/152/commits/79b1dd621ccbd56a4b897258388b2a1bb5586de6

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
The first step for this issue is the creation of a logger that would allow us to have levels, this should be done when we merge #152 
After that, we should go around the code in the more sensitive areas and sprinkle `logger.Debugf`.

**Comment by pivotaljohn** [comment]
> ... and sprinkle logger.Debugf.

Note examples in the description, above, for inspiration for places that could use some logging.

**Comment by aaronshurley** [comment]
Labeling this as `important-soon` as we have had multiple use cases when this capability would have been helpful when troubleshooting users' problems.

**Comment by DennisDenuto** [comment]
Closing. Released in https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.20.0
