### ISSUE TITLE
Improve imgpkg copy UX when copying big bundles 

### ISSUE THREAD

**Issue by iamhsk** [carvel-dev/imgpkg#132]
**Describe the problem/challenge you have**
When copying a big bundle with lots of images and nested bundles, it takes a long time and users do not get any feedback on what is happening after they run the `imgpkg copy` command. This is happening for both copying `--to-tar` and `--to-repo`.

**Describe the solution you'd like**
As a user, I would like to have some visibility into what is going on behind the scenes and also would like the performance of the actual copying to be faster. 

**Anything else you would like to add:**
Faster! ⚡️

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
The main improvements were shipped on version v0.7.0.
The only missing part is the inclusion or not of the spinner that is asked for in this story. Keeping this issue open until we solve this question

**Comment by aaronshurley** [comment]
I believe that the only remaining task for this issue is whether we include a spinner or not. #163 seems to encapsulate that question so I'm going to close this out. Please feel free to reopen if my logic is off.
