### ISSUE TITLE
support env keychain for registry auth

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#14]
ability to use env vars to set registry auth: https://github.com/k14s/kbld/blob/develop/docs/auth.md#via-environment-variables (https://github.com/k14s/kbld/blob/develop/pkg/kbld/registry/env_keychain.go)

**Comment by aaronshurley** [comment]
# Why
To provide an ability to authenticate against multiple registries, consistent with how `kbld` does.
[Updated link to kbld docs](https://carvel.dev/kbld/docs/latest/auth/#via-environment-variables).

## Details
Use a naming schema that is consistent with `kbld`: `IMGPKG_REGISTRY_HOSTNAME`, `IMGPKG_REGISTRY_USERNAME`, `IMGPKG_REGISTRY_PASSWORD`.

Allow the ability to provide multiple registry credentials by using suffixes on the environment variables (e.g. `KBLD_REGISTRY_HOSTNAME_0`.

**Comment by aaronshurley** [comment]
We _think_ that [this documentation](https://carvel.dev/imgpkg/docs/latest/auth/#via-environment-variables) is incorrect. So, there is work to be done here.

**Comment by DennisDenuto** [comment]
TODO:

- [x] backfill tests for env_registry.go from kbld
- [x] backfill imgpkg token and anon keychains
- [x] test cleanup env_keychain_test.go?
- [x] Should we introduce a 'breaking change' from currently supporting "IMGPKG_USERNAME" && "IMGPKG_PASSWORD" to "IMGPKG_REGISTRY_USERNAME" && "IMGPKG_REGISTRY_PASSWORD"? 
- [x] If we change imgpkg's registry environment variables to use "\_REGISTRY\_" then also consider updating:
  - IMGPKG_TOKEN
  - IMGPKG_ANON



Assumption:

The registry username/password 'wins' against an env variable

**Comment by DennisDenuto** [comment]
Currently imgpkg supports env variables:

`IMGPKG_USERNAME` && `IMGPKG_PASSWORD ` && `IMGPKG_TOKEN` && `IMGPKG_ANON`

As part of this story we will *not* remove these env variables, but in order to be consistent with kbld, will introduce new `IMGPKG_REGISTRY_*` env variables.

**Comment by joaopapereira** [comment]
Delivered as part of release v0.7.0
