### ISSUE TITLE
PlainImage should not fall back onto first image in the image index

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#142]
Currently imgpkg pull and copy end up pulling/copying first image of the image index. This is quite misleading because copy succeeds but actually does not copy image index (and other images in it). For pull it's surprising as well -- it's probably better to return an error to let the user know to give single image reference.

(i realized this when trying to `imgpkg copy -i nginx@sha256:... --to-repo dkalinin/private-repo` and not being able to pull that exact digest from private-repo)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
> Currently imgpkg pull and copy end up pulling/copying first image of the image index

When you are talking about the pull here, what do you see happening?
If you execute `imgpkg pull` we do not download any image.

**Comment by joaopapereira** [comment]
this is a `imgpkg copy -i` so we do download the image info

**Comment by joaopapereira** [comment]
I tried the following:
1. Copy nginx:latest to a local registry
```
imgpkg copy -i nginx:latest --to-repo localhost:5000/nginx
copy | exporting 1 images...
copy | will export index.docker.io/library/nginx@sha256:61191087790c31e43eb37caa10de1135b002f10c09fdda7fa8a5989db74033aa
copy | exported 1 images
copy | importing 1 images...
 51.25 MiB / 51.25 MiB [=============================================================================================================================================================================================] 100.00% 3.34 GiB/s 0s
copy | done uploading images
Succeeded
```
2. Download the arm64 Linux OCI Image by SHA and it fails
```
docker pull localhost:5000/nginx@sha256:dcc53ad7391323bd425b95724cde076326a640eda336bd34bc2376ed3614138f
Error response from daemon: manifest for localhost:5000/nginx@sha256:dcc53ad7391323bd425b95724cde076326a640eda336bd34bc2376ed3614138f not found: manifest unknown: manifest unknown
```

Looks like that the first hint that this is not working 100% is in the output of the copy command. `imgpkg` should have copied 8 images + the index image itself but from the output, only 1 image is being copied.

In a different topic, the output of the copy command doesn't look like it takes into account indexes, nevertheless, they are copied.

**Comment by joaopapereira** [comment]
images.NewImages is only used by the PlainImage. Maybe the best approach would be to remove this struct and directly in PlainImage check if the provided Image is an Image or an Index.

Another point is the PlainImage.Pull should fail if the provided PlainImage is not an image, but it should not panic (current behavior)

**Comment by DennisDenuto** [comment]
Released on https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.15.0
