### ISSUE TITLE
Copy Cosign Signature with The Rest of the Images

### ISSUE THREAD

**Issue by iamhsk** [carvel-dev/imgpkg#147]
**Describe the problem/challenge you have**
Currently we don't have a clear path to copy signatures with images. 

**Describe the solution you'd like**
Test out copying signatures using cosign

**Anything else you would like to add:**
N/A

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
available in https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.9.0 via --cosign-signatures flag on copy cmd.
