### ISSUE TITLE
ImageSet#Import panic for internal inconsistency

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#150]
**What steps did you take:**

```
$ imgpkg copy --tar some.tar --to-repo some-repo.com/foo
```

**What happened:**

```
panic: Digest need to be provided: a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: goroutine 59 [running]:
github.com/k14s/imgpkg/pkg/imgpkg/imageset.ProcessedImage.Validate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/k14s/imgpkg/pkg/imgpkg/imageset/processed_images.go:31 +0x185
github.com/k14s/imgpkg/pkg/imgpkg/imageset.(*ProcessedImages).Add(0xc0001f2170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/k14s/imgpkg/pkg/imgpkg/imageset/processed_images.go:49 +0x98
github.com/k14s/imgpkg/pkg/imgpkg/imageset.(*ImageSet).Import.func3(0xc00036faa0, 0xc0000398c0, 0xc0001f2150, 0x0, 0x0, 0x7ffd4cce4248, 0x23, 0x7ffd4cce426c, 0xd, 0x982198, ...)
	github.com/k14s/imgpkg/pkg/imgpkg/imageset/image_set.go:137 +0x1e5
created by github.com/k14s/imgpkg/pkg/imgpkg/imageset.(*ImageSet).Import
	github.com/k14s/imgpkg/pkg/imgpkg/imageset/image_set.go:132 +0x49f
```

seems like we are not checking against err != nil and adding to importedImages regardless (https://github.com/vmware-tanzu/carvel-imgpkg/blob/69d89d174f943959b44840a7915ae618d9ecc871/pkg/imgpkg/imageset/image_set.go#L127-L129). that would be fine, but we are actually pretty strict in Add implementation so will error out with above panic. 

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.6.0
- Docker registry used (e.g. `Docker HUB`): harbor

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cari-lynn** [comment]
Hey @cppforlife how did you create the tar file that produced this panic? It looks based on the panic that the image reference was malformed, however`imgpkg` has strict validation on image references that it won't let you create a tar with an image reference with zero or more than one `@`'s.

If we're able to reproduce this, it would be a better user experience if this panic could be caught and reported as an error.

**Comment by cari-lynn** [comment]
This panic can appear when a network call fails, for example here:
https://github.com/vmware-tanzu/carvel-imgpkg/blob/69d89d174f943959b44840a7915ae618d9ecc871/pkg/imgpkg/imageset/image_set.go#L324
Since we are not checking the error (as @cppforlife described above) before calling `importedImages.Add(processedImage)` there is a panic. 

To fix this issue, check the error returned from `i.tagAndVerifyItem(item, importRepo, registry)` immediately after.

**Comment by cppforlife** [comment]
fixed in https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.9.0
