### ISSUE TITLE
imgpkg panic when a retry happens

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#155]
**What steps did you take:**
When `imgpkg` is copying images to the registry and loses access to the server the retry will panic.

An example can be found in: https://kubernetes.slack.com/archives/CH8KCCKA5/p1622737728282300

**What happened:**
`imgpkg` panics because go-containerregistry closes the channel

**What did you expect:**
On the second retry, it should provide work if the network connection was reestablished. 

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.8.0
- Docker registry used (e.g. `Docker HUB`): any
- OS (e.g. from `/etc/os-release`): any

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help to work on this issue.

**Comment by cppforlife** [comment]
@DennisDenuto it might be good to fix up go-containerregistry to follow following channel pattern - whoever creates channel is responsible for closing it. currently caller creates channel, but MutliWrite closes it making it impossible to reuse the channel against multiple calls (in our use case when we wrap MultiWrite in a retry logic)

**Comment by DennisDenuto** [comment]
@cppforlife That's a good idea. I'll create an issue in go-containerregistry. Might even volunteer to submit a PR on my dev day.

Issue created:
https://github.com/google/go-containerregistry/issues/1038

**Comment by DennisDenuto** [comment]
Merged: https://github.com/google/go-containerregistry/pull/1041

The retry logic (and the channel multiplexing logic) can be removed the next ggcr bump.

Blocked until ggcr (v0.5.1) releases a newer version with merged PR

**Comment by cppforlife** [comment]
initial fix is in https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.9.0

**Comment by joaopapereira** [comment]
we are waiting for version 0.6.0 of ggcr or higher to be able to fully solve this issue

**Comment by aaronshurley** [comment]
v0.6.0 has been cut! Just a heads up, the [folks from ggcr were super responsive](https://github.com/google/go-containerregistry/issues/1094)!
