### ISSUE TITLE
when working with nested bundles, "imgpkg copy --lock-output" always returns digest for the "first" bundle, instead of bundle that was given in -b

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#159]
**What steps did you take:**

```
imgpkg copy --lock staging.lock --to-repo ${TEST_REGISTRY}/imgpkg-debug-release --lock-output release.lock
```

assuming staging.lock points to a bundle that references nested bundles, `release.lock` (may) end up pointing to a nested bundle (instead of root bundle referenced by staging.lock) because writeLockOutput [1] picks last bundle that it finds within processed images.

[1] https://github.com/vmware-tanzu/carvel-imgpkg/blob/develop/pkg/imgpkg/cmd/copy.go#L160-L172

- imgpkg version (use `imgpkg --version`): 0.6.0, 0.7.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Moving this to `carvel accepted`

**Comment by gcheadle-vmware** [comment]
Reproduced using :
- imgpkg binary built from https://github.com/vmware-tanzu/carvel-imgpkg/commit/f5f0bf61e92fd4a44a3a13e4a6f7f58b2848c1fc
- imgpkg-debug public github repo: https://github.com/gcheadle-vmware/imgpkg-debug 
   which was adapted from: https://github.com/andrew-su/imgpkg-debug
   however I found it easier to work with docker hub and the k8slt credentials.

**Comment by joaopapereira** [comment]
After looking a little bit into this issue, for the above case looks like we can just expose the bundle that is being copied.
The harder case is going to be the copy from Tar and creating the BundleLock file. In this case, we do not save any special information about the bundle that was copied into the Tar so we cannot make a good judgment call on which one is the bundle.

We could augment our manifest.json that we store in the tar, further deviating from the OCI standard. Or we could store this information as part of a different file where imgpkg could store any information that is not part of the OCI manifest.json.

**Comment by joaopapereira** [comment]
I started doing the implementation in the branch `bundlelock-incorrect-sha` for reference but it is missing the tar part

**Comment by cppforlife** [comment]
> We could augment our manifest.json that we store in the tar, further deviating from the OCI standard. Or we could store this information as part of a different file where imgpkg could store any information that is not part of the OCI manifest.json.

manifest.json was never close to OCI standard anyway, so we should add it in there in my opinion (similar to what we do with a tag).

**Comment by joaopapereira** [comment]
We continued this conversation in slack in [this thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1624472328087100)

The TLDR is that we should consider having a field in the manifest.json for each image that will allow imgpkg to provide any additional metadata for a particular image. The idea is that `imgpkg` would set an annotation style field that can be read afterward that contains the information if a particular image is the bundle being copied or is an image that is part of a bundle.

**Comment by DennisDenuto** [comment]
for the tarball case:

- Added a `.Label` attribute for each image  referenced in `manifest.json`
-- The implication is that: users will need to re-generate a tarball using a version of imgpkg that contains this fix in order to generate the correct lock file.

**Comment by DennisDenuto** [comment]
Release in https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.13.0

However, Keeping this issue open, as some follow-up refactor commits to remove bundle information from the imagedesc package is still in progress. see https://github.com/vmware-tanzu/carvel-imgpkg/pull/189

**Comment by cppforlife** [comment]
refactor was merged few versions back.
