### ISSUE TITLE
imgpkg fails if location image pull is denied instead of not found

### ISSUE THREAD

**Issue by tomkennedy513** [carvel-dev/imgpkg#166]
**What steps did you take:**
I ran `./imgpkg-darwin-amd64 copy -b "registry.pivotal.io/build-service/bundle:1.2.0" --to-repo gcr.io/cf-build-service-dev-219913/tom/tbs` on imgpkg 0.9.0 and 0.10.0

**What happened:**
I got this error 

```
Error: Reading Images from Bundle: fetching location image: GET https://registry.pivotal.io/v2/build-service/bundle/manifests/sha256-8ab4c32699209412c3f58b4a910aaefc3ace3d1e99b5770dffa20bebda5184fa.image-locations.imgpkg: DENIED: denied; denied
```
**What did you expect:**
I expected it to succeed like it used to on 0.8.0

**Anything else you would like to add:**
it appears the the [location image fetcher only checks for not found errors](https://github.com/vmware-tanzu/carvel-imgpkg/blob/c3c3bdd01be75974854dac4907bc24258f4b0c2b/pkg/imgpkg/bundle/locations.go#L64-L66) and doesn't handle denied (which is what registry.pivotal.io) responds with 

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.10.0
- Docker registry used (e.g. `Docker HUB`):  regsitry.pivotal.io (harbor), trying to copy to gcr
- OS (e.g. from `/etc/os-release`): os x
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
Looks like a regression introduced in 0.9.0. Prioritizing...
