### ISSUE TITLE
when pulling there is no need to check if images are present in the original location

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#179]
**Describe the problem/challenge you have**
When executing `imgpkg pull -b repo.io/some/bundle@sha256:11111111 -o /tmp/bundle` and the bundle was never copied, `imgpkg` tries to check if the Images present in the ImagesLock are present in their original location.
This behavior can cause 2 problems:
1. One extra call to a registry that is not relevant for the current command
2. If the original image is in a registry that needs authentication it will error out unless the user provided the credentials. This does not make sense because we are just checking if the images exist or not, we are not trying to pull the images.

**Describe the solution you'd like**
Stop checking if the images are present in the original location.

The only caveat could be that the current behavior `imgpkg` ensures that all the images provided in the bundle exist. Nevertheless, I do not believe that this is the responsibility of `imgpkg`.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help to work on this issue.

**Comment by joaopapereira** [comment]
This is a performance improvement for the pull command. Also will ensure that the users do not get surprising errors or need to know credentials from other repositories.

**Comment by DennisDenuto** [comment]
part of imgpkg release https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.13.0

**Comment by DennisDenuto** [comment]
part of imgpkg release https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.13.0

implemented from PR https://github.com/vmware-tanzu/carvel-imgpkg/pull/177
