### ISSUE TITLE
docker save fails

### ISSUE THREAD

**Issue by sebgoa** [carvel-dev/imgpkg#184]
**What steps did you take:**
I created an image with `imgpkg -i `, I successfully deployed the manifests that are in it with the kapp-controller

**What happened:**
I wanted to save the image as a tarball to check the file structure inside of it and `docker save` failed

```
$ docker save gcr.io/triggermesh/foo > foo.tar
Error response from daemon: read /var/lib/docker/overlay2/698787214e13f47d0635a718d3d78eb8b173f08577706a7abda9231e711b099f/diff: is a directory
```

**What did you expect:**

to get a tar ball that I could expand

**Comment by DennisDenuto** [comment]
For your use-case try using the `imgpkg pull` command to check the file structure (instead of docker save)

i.e.

`imgpkg pull -i gcr.io/triggermesh/foo  -o /path/to/save/image`

I'm not too sure why `docker save` failed. For that I would try asking in https://github.com/moby/moby

**Comment by DennisDenuto** [comment]
Closing this issue since `docker save` is best answered by docker folk. However, please feel free to ask for additional help if `imgpkg pull` doesn't work for you!

**Comment by sebgoa** [comment]
Thanks for the reply. I appreciate your point of view but I think you closed this a bit fast.

`docker save` works well for any other image, so if it fails it is because there is something different with the structure of the image generated by `imgpkg`. If I were to create an issue upstream in moby they would certainly close like like you did and tell me that this is a `imgpkg` issue, hence leaving me in no man's land. This is not a nice experience for someone trying to test and learn the carvel tools.

second point is that your suggested command does not work with the image, which is a public image so you can also try it.

first, even though I created the image with the `-i` option , I get an error when pulling

```
$ imgpkg pull -i gcr.io/triggermesh/foo -o ./foo
Error: Expected bundle flag when pulling a bundle (hint: Use -b instead of -i for bundles)
```

I actually have to use the `-b` option

```
$ imgpkg pull -b gcr.io/triggermesh/foo -o ./bar
Pulling bundle 'gcr.io/triggermesh/foo@sha256:2aac5a4318c05f978a3817009a0f4b6b9ee545bb5ead86759fd68c79e8c23c43'
  Extracting layer 'sha256:4d3fcd52081c3e14b5d3027c5f303ea1a9c8a8f0a64c01273ff7ae2779726b75' (1/1)

Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```

and I am surprised by the output because I do not see any of the OCI image and runtime manifest, if `docker save` were to work I think I would see all files really present in the image.

**Comment by sebgoa** [comment]
fwiw and for posterity, `crane` does the trick

```
crane pull gcr.io/triggermesh/foo foo.tar
tar -tvf foo.tar
-rw-r--r--  0 0      0         317 Jan  1  1970 sha256:df8579aba80273270191f34a14b28fb23d324f0690f2b6b0d6731b8a97355f82
-rw-r--r--  0 0      0         571 Jan  1  1970 4d3fcd52081c3e14b5d3027c5f303ea1a9c8a8f0a64c01273ff7ae2779726b75.tar.gz
-rw-r--r--  0 0      0         216 Jan  1  1970 manifest.json

tar -xzvf 4d3fcd52081c3e14b5d3027c5f303ea1a9c8a8f0a64c01273ff7ae2779726b75.tar.gz 
x .
x .imgpkg
x .imgpkg/bundle.yml
x .imgpkg/images.yml
x pod.yaml
```

**Comment by DennisDenuto** [comment]
> I think you closed this a bit fast

I appreciate the feedback. i'll take that into account next time :-) 

>  I am surprised by the output because I do not see any of the OCI image and runtime manifest

Fair enough! fwiw, `imgpkg pull` places the contents of the layers belonging to the image onto disk for you.

If you wanted to download an image and have access to it's manifest, layers, config etc (almost an oci-layout format) you could copy the bundle to a tarball

i.e.
```
imgpkg copy -b gcr.io/triggermesh/foo --to-tar ./foo.tar
```

> crane does the trick

hmmm, my intuition is pointing me back to something going wrong with `docker save` and less about the "structure of the image generated by imgpkg"

Glad you figured it out in the end!
