### ISSUE TITLE
Copy on insecure registries

### ISSUE THREAD

**Issue by andmagom** [carvel-dev/imgpkg#192]
**What steps did you take:**
I would like to copy images between insecure registries, I executed this command
`imgpkg copy --registry-insecure -b registry.192.168.20.40.nip.io:5000/myimage --to-repo registry.192.168.20.40.nip.io:5000/myimage2`

**What happened:**
I got this error
![image](https://user-images.githubusercontent.com/13066717/125817264-6973cced-5041-4cb5-aa41-6224211a5d33.png)

**What did you expect:**
If I set the --registry-insecure flag, I should like to be able to copy images between insecure registries

**Environment:**

- imgpkg version (use `imgpkg --version`): imgpkg version 0.14.0
- Docker registry used (e.g. `Docker HUB`):  registry:v2 - docker image
- OS (e.g. from `/etc/os-release`): Mac OS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

**Comment by DennisDenuto** [comment]
Can reproduce. The image references provided to `MultiWrite` are losing the `insecure` option, hence when the ggcr library 'pings' the registry it doesn't 'fallback' to using http.

https://github.com/vmware-tanzu/carvel-imgpkg/blob/ee3d2f72ca3f9750939ca366097454074d2d0d04/pkg/imgpkg/registry/registry.go#L127

**Comment by DennisDenuto** [comment]
Submitted PR https://github.com/vmware-tanzu/carvel-imgpkg/pull/197

**Comment by andmagom** [comment]
Thanks Dennis !

**Comment by DennisDenuto** [comment]
Released on https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.15.0
