### ISSUE TITLE
Help output for push command claims `-f -` is supported

### ISSUE THREAD

**Issue by gabegorelick** [carvel-dev/imgpkg#195]
**What steps did you take:**
`imgpkg push --help` claims that `-f` supports `-`, presumably as an alias for stdin:

> -f, --file strings                                Set file (format: /tmp/foo, -) (can be specified multiple times)

![image](https://user-images.githubusercontent.com/610129/126244105-9e0153f5-178a-4e85-bd54-c6b0116beef3.png)

**What happened:**
`imgpkg push -f -` returns the following error:

> Error: lstat -: no such file or directory

`imgpkg push -f /dev/stdin` returns this error:

> Error: This directory is not a bundle. It it is missing .imgpkg/images.yml

**What did you expect:**
I expected that `imgpkg push -f -` would work. 

**Anything else you would like to add:**
Should probably remove reference to `-f -` from `imgpkg push --help`. And maybe make a note that it requires a directory.

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.14.0
- Docker registry used (e.g. `Docker HUB`): n/a
- OS (e.g. from `/etc/os-release`): macOS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Thanks for creating this issue!

Submitted PR https://github.com/vmware-tanzu/carvel-imgpkg/pull/196

**Comment by DennisDenuto** [comment]
Released on https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.15.0
