### ISSUE TITLE
imgpkg tag list --digests as False by Default

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/imgpkg#20]
`imgpkg tag list` features a `--digests` option that is described as `Include digests (default true)`. Since the option is [true by default](https://github.com/vmware-tanzu/carvel-imgpkg/blob/61f962a8b5de930773140dcc8cd03ff320cc1e1a/pkg/imgpkg/cmd/tag_list.go#L38), it will always be true regardless of whether or not it is specified. This calls into question whether the flag should exist at all or whether it should be false by default. 

**Edit**

Repurposing this issue around changing the default to `false` for `--digests` for `imgpkg tag list` as documented in this [comment](https://github.com/vmware-tanzu/carvel-imgpkg/issues/20#issuecomment-732453428).

**Comment by danielhelfand** [comment]
Closing, as cobra requires `imgpkg tag list -i ... --digests=false` with an explicit `=` included with false.

**Comment by danielhelfand** [comment]
Reopening this to have it be a discussion around whether to have `--digests` as false by default as it can be expensive to pull down several digests. So for images with many tags, it might be better to not pull down digests unless asked for by the user.

**Comment by joaopapereira** [comment]
Can I suggest a different name for this flag:
`--enable-digests`
`--with-digests`
`--get-digests`

Maybe this will help clear the usage of this flag and would change the flag type to be a boolean flag. If it is present it enables the retrieval of the digests if it is not present it would not retrieve the digests

**Comment by cppforlife** [comment]
@joaopapereira within carvel we tried to have consistent noun based flags to indicate feature. value of the flag determines whether it's enabled or disabled. (some of the thinking about that is that flag name should not influence the value of the flag. it's also not great to have multiple flags --disable-blah, --enable-blah)

**Comment by joaopapereira** [comment]
That is good background information.
My assumption was that we would have a default behavior and we would just have flags that would change that behavior.
In the current example, the behavior by default would be not to retrieve digests, and we would have a flag to signal that we want to retrieve them.

Of course, if we needed a flag that could have multiple values (not boolean) then I would definitely use a flag like `--blah=10`.

**Comment by aaronshurley** [comment]
Consider doing some upfront research to have some time estimates as to how long it takes to get digests. Use this information to form a more educated opinion on what the UX should be.

**Comment by iamhsk** [comment]
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.

**Comment by cppforlife** [comment]
i think we should also add sibling command, something like `imgpkg tag resolve foo:v1.0.0` to return digested ref so that users are able to get an immutable reference (even though this overlaps with kbld, i think it makes sense since we are providing `imgpkg tag list`)

**Comment by cppforlife** [comment]
https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.17.0 included change to "tag list" and added "imgpkg tag resolve".
