### ISSUE TITLE
ensure that root bundle tag is added/updated last during "imgpkg copy"

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#211]
**Describe the problem/challenge you have**

currently, if you are continuously running `imgpkg copy -b foo:latest --to-repo bar`, `bar:latest` will get updated in parallel with all the other referenced assets. this may present a challenge to consumers who are pulling `bar:latest` since they could receive `bundle:latest` before referenced assets are copied (and *.image-locations.imgpkg is made).

**Describe the solution you'd like**

this ultimately is related to when we add/update tag (in above example latest tag). we need to update tag at the last moment when all the related resources are in place: referenced blobs, root bundle blob, *.image-locations.imgpkg. we probably need to do this in order from inner bundles, to outer bundles (but can still parallelize writing of all image-locations.imgpkg images).

i dont believe we do this today.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Thanks for the issue.

I think this captures a potential race condition with tools / pipelines waiting for a bundle. Prioritizing as something to work on soon.
