### ISSUE TITLE
ImageLocations is not generated when source is tar

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#212]
**What steps did you take:**
looked at code [0]

**What happened:**
it does not look like when tar is source we call NoteCopy which means we are not generating *.image-locations.imgpkg images later used for pull optimization.

**What did you expect:**
expected ImageLocations record to be generated.

**Anything else you would like to add:**
this issue should probably be dealt in a context of https://github.com/vmware-tanzu/carvel-imgpkg/issues/211

[0] https://github.com/vmware-tanzu/carvel-imgpkg/blob/7d2fd285eaa493c5460b5739104e6876fcc04217/pkg/imgpkg/cmd/copy.go#L110-L116

**Environment:**

- imgpkg version (use `imgpkg --version`):
- Docker registry used (e.g. `Docker HUB`): 
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
This looks like it was fixed as part of the "Copy Tweaks" PR? https://github.com/vmware-tanzu/carvel-imgpkg/pull/215


Is that correct @cppforlife ?

**Comment by DennisDenuto** [comment]
Thanks for the issue

Looking at the code this is still an issue.

https://github.com/vmware-tanzu/carvel-imgpkg/blob/d61feedd8506965bcfcb660dfff86105bf9a0166/pkg/imgpkg/cmd/copy_repo_src.go#L67-L80

**Comment by joaopapereira** [comment]
Fixed in version [0.23.0](https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.23.0)
