### ISSUE TITLE
Certs do not verify when running on windows

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#22]
This issue was discussed in https://github.com/vmware-tanzu/carvel-kbld/issues/75.

Since `imgpkg` inherited some functionality from `kbld` we will need to fix it in `imgpkg` as well.

Notes
- see [kbld's comment](https://github.com/vmware-tanzu/carvel-kbld/issues/75#issuecomment-906670951) about reproducing this again before starting implementation.

**Comment by pivotaljohn** [comment]
Next step: verify whether this is still an issue.

**Comment by tezizzm** [comment]
@pivotaljohn As of the [0.19 release](https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.19.0) this is still an issue:

![image](https://user-images.githubusercontent.com/5050479/134991075-e2a1bf89-8615-4761-b457-79d67f52c2c8.png)

**Comment by andreizimin** [comment]
adding  `--registry-verify-certs='False'` seems to by-pass the issue
