### ISSUE TITLE
Improve retry logic around flakey registries

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/imgpkg#232]
**Describe the problem/challenge you have**
- related to https://github.com/google/go-containerregistry/issues/1113

There are scenarios when a registry returns an error and imgpkg does *not* retry when it should. (since retrying would resolve the issue)

**Describe the solution you'd like**
imgpkg to retry errors from a registry, even if the actionable error is UNKNOWN.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
With the bump to go-containerregistry to version 0.7.0 this issue is solved.

Present in version 0.23.0 of `imgpkg`
