### ISSUE TITLE
reconsider how registry matching is done in env keychain

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#235]
**Describe the problem/challenge you have**

currently we only match by hostname. to make imgpkg more interoperable with k8s we may want to support more flexible matching:
Fix soon:
- [x] support ignoring of http/https scheme
  - https://github.com/vmware-tanzu/carvel-imgpkg/issues/234
- [x] ignore v1/v2 suffix on dockerhub? 

Requires more investigation:
- [x] support matching by globs? k8s cred provider related code has some matching
- [x] support matching by repository path (e.g. support credentials for same registry but under different paths)
    - https://github.com/vmware-tanzu/carvel-imgpkg/issues/226

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Closing. This has been resolved in https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.18.0
