### ISSUE TITLE
allow deletion of images/bundles

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/imgpkg#238]
**Describe the problem/challenge you have**
imgpkg delete command to compliment push and pull

**Describe the solution you'd like**
`imgpkg delete -i` `imgpkg delete -b`

Provide a way to delete an image / bundle. Furthermore, allow to delete copied bundles/images.

**Anything else you would like to add:**
from this slack convo: https://vmware.slack.com/archives/CUK1X0Z8Q/p1630886629110900

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by GrahamDumpleton** [comment]
More complete version of issue created at same time:

* https://github.com/vmware-tanzu/carvel-imgpkg/issues/239

**Comment by DennisDenuto** [comment]
Thanks @GrahamDumpleton i'll close this issue in favor of the one you created :-)
