### ISSUE TITLE
imgpkg crashes with `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by kdvolder** [carvel-dev/imgpkg#244]
**What steps did you take:**

See: https://github.com/spring-projects-experimental/spring-boot-observer/blob/main/application-live-view-convention-service/01-setup-convention-controller-in-kind.sh#L21

**What happened:**

The process seems to start okay then crashes with a segmentation fault.

**What did you expect:**

To execute and 'materialize' the bundle contents on the file system.

**Anything else you would like to add:**

I'm really totally at a loss what the error means. Seems like a bug to me, but it ma just as well be something I am doing wrong. I have no idea. At the very least, if its something I'm doing wrong, it certainly would be nice if the error message provided a better explanation of what the problem might be. 

**Environment:**

- imgpkg version (use `imgpkg --version`):

```
$ imgpkg -v
imgpkg version 0.5.0
```

- Docker registry used (e.g. `Docker HUB`): 

harbor-repo.vmware.com

- OS (e.g. from `/etc/os-release`):

Ubuntu 18.04.5 LTS 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Hi @kdvolder  - Thanks for creating this bug

I am unable to access: https://github.com/spring-projects-experimental/spring-boot-observer/

So I am unable to see what command you are running.

However, I noticed that the version of imgpkg you are using is a few versions out of date.

Can you try updating to the latest (v0.17.0) and trying again?

**Comment by kdvolder** [comment]
The above repo linked repo is private not sure you'd have access. This is the bit of ths script that matters:

```
export DOCKER_REPO=harbor-repo.vmware.com/tanzu_sbo
export CONVENTION_CONTROLLER_VERSION=v0.4.0 # update when we cut the initial release
imgpkg copy --tar ~/Downloads/convention-controller-bundle-${CONVENTION_CONTROLLER_VERSION}.tar --to-repo ${DOCKER_REPO?:Required}/convention-controller-bundle || echo fails sometimes, ignore
```

Also the tar file being referenced is from this page: https://github.com/vmware-tanzu/convention-controller/releases
Specifically: https://github.com/vmware-tanzu/convention-controller/releases/download/v0.4.0/convention-controller-bundle-v0.4.0.tar

Also in a private repo but if you are in VMware you should be able to get access to it.

**Comment by kdvolder** [comment]
> However, I noticed that the version of imgpkg you are using is a few versions out of date

REally? I though I just downloaded a fresh one. Let me check and see...

**Comment by kdvolder** [comment]
No more error with v0.17. So closing.

**Comment by kdvolder** [comment]
Thanks for the quick reply. As to how I ended up with old version. It seems I downloaded the latest, but also still had another older binary still in 'Downloads' folder and somehow that one got installed and used instead. It might be useful if the download files included the version in the file name. E.g. `imgpkg-linux-amd64-v0.17` instead of `imgpkg-linux-amd64`. 

I think that would make mistakes installing an old version by accident less likely. Just a suggestion, not sure how easy it would be to do this, it is of course entirely up to you to decide if its worth doing this :-)

**Comment by DennisDenuto** [comment]
Thanks for that additional context @kdvolder 

My main concern with renaming the binary to include the version would be breaking downstream consumers that may be relying on that filename.

Although, I think if we start seeing more issues around the problem you stated, we would consider it as a viable option :-)
