### ISSUE TITLE
Prepare lockfiles Package for Use by kbld

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/imgpkg#25]
As part of `imgpkg` refactoring (#24), issue #17 was closed. #17 describes moving ImagesLock/BundleLock into their own package. In #24, these lock files were moved to a package called [`lockfiles`](https://github.com/vmware-tanzu/carvel-imgpkg/tree/f16abb7db573cda6eace814fd159262f562869bd/pkg/imgpkg/lockfiles). 

This issue is being opened to document any changes needed to convert `kbld` to using `imgpkg`'s `lockfiles` package for using its [ImageLock definition](https://github.com/vmware-tanzu/carvel-imgpkg/blob/f16abb7db573cda6eace814fd159262f562869bd/pkg/imgpkg/lockfiles/lock_files.go#L36). `kbld`'s [implementation of ImagesLock](https://github.com/vmware-tanzu/carvel-kbld/blob/7b1b89d1aae2ca8855ccfdd9bf6ec32926710baa/pkg/kbld/config/images_lock.go#L18) differs a bit, and we should figure out what needs to be done to convert the `imgpkg` concept of an ImagesLock to more closely align and the ImagesLock defined in `kbld` can be removed.

This issue can be closed when:
1. There is a clear idea around changes that need to be made to the `imgpkg` ImageLock definition to support `kbld` (if any)
2. Work has been carried out to make it so `kbld` can import `imgpkg`'s `lockfiles` package for its own use cases with ImagesLocks

**Comment by joaopapereira** [comment]
After closing this issue we should create a new issue in [kbld](github.com/vmware-tanzu/carvel-kbld) to start using the `lockfiles` package from `imgpkg`.

**Comment by cppforlife** [comment]
lockconfig pkg fixed made available as part of #48.

**Comment by gcheadle-vmware** [comment]
Closing issue with release of version 0.3.0
