### ISSUE TITLE
imgpkg pull recursive is really cool for machines, but less great for users

### ISSUE THREAD

**Issue by voor** [carvel-dev/imgpkg#291]
**Describe the problem/challenge you have**
I have started doing a fair bit of PackageRepository work, which is causing me to dig into the actual contents of a Package fairly often.  Packages are great, but since Package authors are very new to Packages the current results are of extremely varying quality.  This results in me very often inspecting a Package, figuring out the bundle that is backing it, pulling that bundle down, and looking at the contained Kubernetes manifests so I can rapidly iterate on overlays or other missing resources (adding new secrets, missing service accounts, etc.).  I recently learned of `--recursive` and was blown away with "where has this been all my life" since now I no longer have to individually pull each package when I encounter it.  Unfortunately, the results:

```
.
└── bundles
    ├── sha256-039663e81f417b88e71f6197b5bd522d0483841b84c85ed31238c3020e73ae28
    │   └── config
    ├── sha256-0a241843322296b4a4c363fbe2a1762248718179cc377182db20c7f49ce8837b
 ...
    ├── sha256-a1b60baa8a42860cb1d4c510fc0e5ad2f40dd879a5f601c161063f76b8d9c976
    │   └── config
    ├── sha256-aed1df0002a800e9aac41fbbba524aeb0327bb1d96a390082e1f6b62164bf8e3
    │   └── config
    │       ├── overlay
    │       ├── resources
    │       └── upstream
    │           └── operator
    │               └── resources
    │                   ├── crds-v1
    │                   └── operator
    ├── sha256-c0ece472adf0f93efbff9ef12b0b0bd8fb68a7205d4e963f5a31bc35e5ba819c
    │   └── config
    ├── sha256-c1b63312ca2333298ede54f6121f17c53bb7d1b68256dbd6dccbc1ba88abded1
    │   └── config
    │       ├── build-service
    │       ├── dependency-updater
    │       ├── kpack
    │       ├── pod-webhook
    │       ├── secret-syncer
    │       ├── stacks-operator
    │       └── warmer
    ├── sha256-c844555c9260900d54004b7096d938da2c0ba41a63cb379d767a70b4dee8147e
    │   └── config
    ├── sha256-d8f3ddd7475bb9ba7a550ee10ce8aba82ae3e1f15db178bc7c616967ed2e2f88
    │   └── config
    ├── sha256-dbd55127d35c8634cb27bdffc2d5e1574b660ddbb032926d00822e9881ca30c6
    │   └── config
    ├── sha256-ddab81804d0489113fd03b5057946001fbb2c322a58b39798ccaaac0f0eafb03
    │   └── config
    ├── sha256-e3af6fbbbce1defd461e9d7e2800bca44ec98e5901c4cd1ea428cf9acc9c7616
    │   └── config
    ├── sha256-ee1d48f63f6cea7b3faf243eff911ae87627309d81eafdf746495e2c7dfef440
    │   └── config
    ├── sha256-f173696d119d0dc9adaa32c7c4e42b8444ee5f32ca845ccd83e0f0995d6f9a1a
    │   └── config
    ├── sha256-f2ec6e788b45e9a66ee361f1457f3f1446d8aa9a329f35b25dfc1a49e97cd767
    │   └── config
    │       └── tutorials
    │           └── resources
    └── sha256-fcf95067b792e8a043cc51638fcd0001875d2895bf09349b34a9d2b0056850a1
        └── config
```

Are not particularly user friendly for rapidly figuring out which Package is associated with which bundle.

**Describe the solution you'd like**
I'm wondering if there's something grander brewing here, that might align with other efforts for `kbld` and `imgpkg` that might make this experience more user friendly -- should `kbld` have an optional `kbld.carvel.dev/friendly-name` annotation that could exist or something that might trigger this process to name the folders something "prettier" when warranted?  I don't know, and I'm open to discussion or hearing other things that might make this nicer.

**Anything else you would like to add:**
This experience is already better than having to find the sha and imgpkg pull that sha, because now I just find the sha in the corresponding folder structure, so :bow: for improving the process slightly already.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Thanks for reaching out @voor 

Do you think it would be helpful a UX like:
```
$ imgpkg describe -f bundle-folder

Bundle SHA: aaaaad700949154e429d28661d01c99d53a38af0d5275842ccbf0bf6dbef8ca4
Tags: latest, v1.0.0

Authors:
  Carvel Team <carvel@vmware.com>
Websites:
  carvel.dev/imgpkg
Metadata:
  - Some Version: 1.0.0
  - Other Information: Some text here

Copy Strategy: SingleRepository

Images:
  - new.registry.io/simple-app-install-package@sha256:d211dd700949154e429d28661d01c99d53a38af0d5275842ccbf0bf6dbef8ca4 (Bundle)
    Origin: my.registry.io/bundle1@sha256:d211dd700949154e429d28661d01c99d53a38af0d5275842ccbf0bf6dbef8ca4
    Location In Disk: /tmp/bundle1/.imgpkg/bundles/sha256-d211dd700949154e429d28661d01c99d53a38af0d5275842ccbf0bf6dbef8ca4
    Images:
      - new.registry.io/simple-app-install-package@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        Origin: registry.io/img1@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        Location In Disk: /tmp/bundle1/.imgpkg/bundles/sha256-4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        Annotations:
          kbld.carvel.dev/id: my.registry.io/simple-application

      - new.registry.io/simple-app-install-package@sha256:47ae428a887c41ba0aedf87d560eb305a8aa522ffb80ac1c96a37b16df038e0f
        Origin: registry.io/img2@sha256:47ae428a887c41ba0aedf87d560eb305a8aa522ffb80ac1c96a37b16df038e0f
        Location In Disk: /tmp/bundle1/.imgpkg/bundles/sha256-47ae428a887c41ba0aedf87d560eb305a8aa522ffb80ac1c96a37b16df038e0f
  - new.registry.io/simple-app-install-package@sha256:47ae428a887c41ba0aedf87d560eb305a8aa522ffb80ac1c96a37b16df038e0f
    Origin: registry.io/img2@sha256:47ae428a887c41ba0aedf87d560eb305a8aa522ffb80ac1c96a37b16df038e0f
    Location In Disk: /tmp/bundle1/.imgpkg/bundles/sha256-47ae428a887c41ba0aedf87d560eb305a8aa522ffb80ac1c96a37b16df038e0f

```

**Comment by voor** [comment]
I still do this in a fairly regular basis, always in the context of pulling a Package Repository.  I'm thinking, based on your UX example, you're looking at this more broadly as "given a recursive imgpkg bundle, with fairly limited information derived from the lock file how do I unpack this"

I'm not sure that'll have the desired outcome of giving me a friendly "scannable" way to read through the package names.

**Comment by joaopapereira** [comment]
I understand what you mean, nevertheless `imgpkg` does not know what you are packing as part of the Bundle. The creator can be bundling a PackageRepo, or a Package, or some YAML files, or some binaries, or just an application.

What kind of information are you looking for when you are trying to get the bundles recursively?
