### ISSUE TITLE
Bump `go-containerregistry` dependency

### ISSUE THREAD

**Issue by jpmcb** [carvel-dev/imgpkg#325]
**What steps did you take:**
imgpkg is using `v0.7.0` of `github.com/google/go-containerregistry/`. Can we upgrade to the latest sha of go-containerregistry to capture the latest dependency bumps from that library?

Related: https://github.com/google/go-containerregistry/pull/1271

**What happened:**
Received a security alert for `github.com/opencontainers/image-spec` which is a dependency in `github.com/google/go-containerregistry`

**What did you expect:**
`imgpkg` to provide the latest dependencies and libraries

**Environment:**

N/a

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Thanks for reporting we already have PR #324 that I hope to merge somewhere today and maybe do a release next week.

**Comment by jpmcb** [comment]
Awesome!!! Should have looked at the PRs 😂

**Comment by joaopapereira** [comment]
Unfortunately, we are stuck because a change in the Blob Storage is making our performance tests go OOM.

Need to decide if we are ok not running performance tests in windows or if we should invest time triaging and fixing the issue in ggcr

**Comment by jpmcb** [comment]
This still stands and would be great to also capture the bump to `docker/distribution` v2.8.0+ [related to this advisory](https://github.com/advisories/GHSA-qq97-vm5h-rrhg)
