### ISSUE TITLE
Introduce tag that gives visibility into source image / repository

### ISSUE THREAD

**Issue by joshrosso** [carvel-dev/imgpkg#331]
When using `imgpkg copy -b`, especially recursively against many packages, we end up with a repository full of tags. This is great, but makes things hard to identify without extra tooling.

For example:

![image](https://user-images.githubusercontent.com/6200057/152581938-5dd5c59f-9d70-4341-94f0-18e6b56d91e1.png)

Ideally, there'd be a tag that could help us better identify the source image. For example:

![image](https://user-images.githubusercontent.com/6200057/152582004-ac484353-31a1-42ef-a9e0-cf766bbd6a6e.png)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by alexgaganashvili** [comment]
@joshrosso , could you provide more context/details into this issue? I'm just wondering how I can reproduce it so that I can better understand what should be improved.
Thanks.

**Comment by cppforlife** [comment]
> could you provide more context/details into this issue

if you run `imgpkg copy -b ... --to-repo bar.com/foo/blah/dst/repo` then all assets are copied over into the same repo (e.g. /foo/blah/dst/repo). such images will have standard imgpkg tags like `sha256-....imgpkg` and will not have any indication from the registry perspective that it was cert-manager image for example.

a practical improvement that could be made is: in addition to regular imgpkg tags, one can add "mangled" human friendly tag (e.g. based on screentshot above, tag could be: `tce-cert-manager-<some randome bits>`).

**Comment by alexgaganashvili** [comment]
@cppforlife , thanks for providing more details.
Here's a PR: https://github.com/vmware-tanzu/carvel-imgpkg/pull/333

**Comment by joaopapereira** [comment]
I was talking with Dmitriy and we were thinking about the impact of `imgpkg` creating 2 tags per image. In our point of view, it feels like we do not need 2 tags.
The suggestion that we would like to do is to instead replace the current tag that is generated by `imgpkg` with a new format.

Let's imagine the following image:
`my.registry.io/some/application@sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be`
Currently `imgpkg` generates a tag that looks like `sha256-669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be.imgpkg`. Instead we would recommend changing this tag to `some-application-sha256-669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be.imgpkg`

Why this tag:
- we assume that if we keep the suffix `.imgpkg` it would be easier for registry admins if they want to create/maintain rules for replication of images, they can just use one that looks like `*.imgpkg`
- Using the full SHA will prevent us from having any kind of collisions between tag names

A current restriction is that the tag cannot have a length bigger than 128 chars. This might be a constraint that might cause some issues when we create a tag and maintain the 2 rules above. With this, the tag can only accommodate is 49 characters related to the repository. Do y'll think this might be enough space to keep the name of the images?

If the name that we want to preserve is bigger than 49 we suggest that we use the last 49 characters of the repository:
ex: `my.registry.io/my-super-interesting-product/application-power/controler@sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be` -> `r-interesting-product-application-power-controler-sha256-669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be.imgpkg`.


Another point is that we might not want this behavior by default, so we would like to have a flag from the command line that would enable this behavior. Something like `--repository-based-tags` or something similar.


I know that @alexgaganashvili already has a PR for this change, sorry for commenting late in this issue.

**Comment by alexgaganashvili** [comment]
I like the the idea of enabling this behavior through a flag such that in addition to `sha256-669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be.imgpkg` another tag (considering the constraints described above) `some-application-sha256-669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be.imgpkg` (or `some-application-669e010b`) would be generated.
If the status quo behavior is completely removed, will it somehow affect an automation tool that relies on the current behavior?

**Comment by joaopapereira** [comment]
Not to our knowledge, but we can try to check in the slack channel and get some feedback.

**Comment by ZihanJiang96** [comment]
+1 for this, I understand that the extra tags ends with `.imgpkg` are inevitable, 

but i really like the idea that we add the `some-application-` prefix to the new tags generated by `imgpkg copy` cmd

**Comment by joaopapereira** [comment]
Since we got no feedback against this new behavior lets go ahead and implement it
