### ISSUE TITLE
Add Option to Use Dockerhub Proxy during Tests

### ISSUE THREAD

**Issue by alexgaganashvili** [carvel-dev/imgpkg#335]
Dockerhub has rate limits.

If there's an Artifactory registry to which you have access, you can proxy your pulls via it.
For example, an environment variable - such as DOCKERHUB_PROXY - could be assigned an Artifactory proxy value (i.e., my-registry.company.local/dockerio-proxy-cache). If the env variable is not set, use the default docker.index.io.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
This issue was fixed by #338

Was released with version v0.26.0 of `imgpkg`
