### ISSUE TITLE
The "source <(imgpkg completion bash)" command outputs an error message

### ISSUE THREAD

**Issue by itaytalmi** [carvel-dev/imgpkg#342]
**What steps did you take:**
[A clear and concise description steps and any files that can be used to reproduce the problem.]

Added `source <(imgpkg completion bash)` to my `/etc/profile` so it would automatically load.

To reproduce the issue, you can simply run `source <(imgpkg completion bash)`.

**What happened:**
[A small description of the result]

Got the following error message:

```text
Succeeded: command not found
```

This is because the `imgpkg completion bash` commands outputs a `Succeeded` string at the end, which is not a valid command, and when used with `source`, bash tries to execute it.

Bash completion does work, though.

**What did you expect:**
[A description of what was expected]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

As a workaround, I'm using the following:

```bash
source <(imgpkg completion bash | grep -v Succeeded)
```

This removes the `Succeeded` string from the output, so the error doesn't occur.

Same issue also occurs with kapp, as I described here:
https://github.com/vmware-tanzu/carvel-kapp/issues/447

This issue doesn't occur with ytt, because `ytt completion bash` doesn't output the `Succeeded` string.

**Environment:**

- imgpkg version (use `imgpkg --version`): `0.25.0`
- Docker registry used (e.g. `Docker HUB`): Irrelevant
- OS (e.g. from `/etc/os-release`): Using `Linux Ubuntu 20.04.4 LTS (Focal Fossa)` and `macOS Monterey 12.2.1`, but this issue occurs on any bash.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Definitely, this looks like a bad experience. Going to change the label from carvel triage to carvel accepted.
If you are interested in contributing a solution we would be more than happy to take it.

**Comment by itaytalmi** [comment]
Hi @joaopapereira, kapp team has released a fix for this as mentioned here
https://github.com/vmware-tanzu/carvel-kapp/issues/447#issuecomment-1075939861
The same thing can be implemented here. It would be nice to have the `--tty=false` option in imgpkg as well.

**Comment by praveenrewar** [comment]
Hey @joaopapereira! We recently resolved this issue in kapp and kctrl by setting different default values of tty flag for different commands. For example, in kapp `deploy` and `delete` command have default value set as true but other commands have the default value as false. 
Would a similar approach work in imgpkg as well? (I am thinking it would, but not sure if there would be any side effects)
I would be happy to work on a PR if the idea sounds good :)

**Comment by joaopapereira** [comment]
We can give that a try, feel free to create a PR :D

**Comment by praveenrewar** [comment]
I noticed that the default tty value in imgpkg is false (in kapp it was true). The issue with bash completion is there because the bash completion command is being added after `ConfigureUI` is called. We only need to add it after `DisallowExtraArgs` is being called.
(I will create a PR for this change)
