### ISSUE TITLE
User defined http transport is not respected

### ISSUE THREAD

**Issue by scothis** [carvel-dev/imgpkg#362]
**What steps did you take:**

When using imgpkg as a library, we define a custom http transport in order to configure the TLS config and provide that to imgpkg as a ggcr option via [`remote.WithTransport()`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote#WithTransport)

**What happened:**

The `WithTransport` option is no longer respected. In our case, imgpkg's attempt to create its own transport fails the ping with an untrusted cert.

**What did you expect:**

A user defined transport should be respected.

**Anything else you would like to add:**

This behavior appears to have regressed as a result of https://github.com/vmware-tanzu/carvel-imgpkg/pull/334

**Environment:**

- imgpkg version (use `imgpkg --version`):
- Docker registry used (e.g. `Docker HUB`): 
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
After some looking around in the code `imgpkg` does not use `regOpts ...regremote.Option` so I am not quite sure why we have that as part of our interface.

I will remove that from the Arguments of the `NewSimpleRegistry` function.

To do not leave yll hanging I will create a different function that you can provide an HTTP transport directly to it.

**Comment by scothis** [comment]
> To do not leave yll hanging I will create a different function that you can provide an HTTP transport directly to it.

If you're going to pull support for `remote.Options`, don't bother. We also use these options to define custom auth via k8schain. It sounds like we shouldn't be using imgpkg as a library.
