### ISSUE TITLE
Imgpkg copy failing to move bundle between same registry, different project

### ISSUE THREAD

**Issue by DennyHoang** [carvel-dev/imgpkg#367]
**What steps did you take:**

Update to v0.26.0 and/or v0.27.0 from v0.25.0 and using `imgpkg copy` to move a bundle between same registry, different project.

**What happened:**
After the update, `imgpkg copy` started to fail for my usage.
`v0.25.0` works however.

**What did you expect:**
I expected the `imgpkg copy` to continue to work.

**Anything else you would like to add:**
Environment variables set:
```bash
IMGPKG_REGISTRY_HOSTNAME_0=${REGISTRY}/${PROJECT_1}
IMGPKG_REGISTRY_USERNAME_0=<Bot user for above host/project>
IMGPKG_REGISTRY_PASSWORD_0=<Pass>

IMGPKG_REGISTRY_HOSTNAME_1=${REGISTRY}/${PROJECT_2}
IMGPKG_REGISTRY_USERNAME_1=<Bot user for above host/project>
IMGPKG_REGISTRY_PASSWORD_1=<Pass>
```

Command used:
```bash
imgpkg copy -b "${REGISTRY}/${PROJECT_1}/${IMAGE}:${TAG}" --to-repo "${REGISTRY}/${PROJECT_2}/${IMAGE}"
```

```
$ imgpkg copy -b <REGISTRY>/<PROJECT_1>/<IMAGE>:1.1.0 --to-repo <REGISTRY>/<PROJECT_2>/<IMAGE>
copy | exporting 3 images...
copy | will export <REGISTRY>/<PROJECT_1>/<IMAGE>@sha256:b473574622c41251fa4a7b62ff7e7cfb25bc4b394eb439bdef69972365e1c89a
copy | will export <REGISTRY>/<PROJECT_1>/<OTHER_IMAGE>@sha256:0fde65bf137374e37cbd983e70a3fb683a12822d4dc4967f4e3d7fdf091025f3
copy | will export <REGISTRY>/<PROJECT_1>/<OTHER_IMAGE_2>@sha256:e6bf93b0460bc4666d88d942468ebe557f0aac365decd70e77ffcea892ab72a8
copy | exported 3 images
copy | importing 3 images...

19.93 MiB / 48.36 MiB [------------------------------------------------------------------->________________________________________________________________________________________________] 41.21% 1.43 MiB p/s
Error uploading images: POST https://<REGISTRY>/v2/<PROJECT_2>/<IMAGE>/blobs/uploads/?from=<PROJECT_1>%2F<IMAGE>&mount=sha256%3A1ed0e4ef744e7e2688d563427f63df35ab43a3056f0b00baa8d239b4d77b52b5: UNAUTHORIZED: unauthorized to access repository: <PROJECT_1>/<IMAGE>, action: pull: unauthorized to access repository: <PROJECT_1>/<IMAGE>, action: pull

19.93 MiB / 48.36 MiB [------------------------------------------------------------------->_______________________________________________________________________________________________] 41.21% 17.92 MiB p/s

copy |
copy | done uploading images

imgpkg: Error: POST https://<REGISTRY>/v2/<PROJECT_2>/<IMAGE>/blobs/uploads/?from=<PROJECT_1>%2F<IMAGE>&mount=sha256%3A1ed0e4ef744e7e2688d563427f63df35ab43a3056f0b00baa8d239b4d77b52b5:
  UNAUTHORIZED: unauthorized to access repository: <PROJECT_1>/<IMAGE>, action: pull: unauthorized to access repository: <PROJECT_1>/<IMAGE>, action: pull

$ imgpkg version
imgpkg version 0.26.0

Succeeded
```

**Environment:**

- imgpkg version (use `imgpkg --version`): v0.26.0 and v0.27.0
- Docker registry used (e.g. `Docker HUB`): Harbor
- OS (e.g. from `/etc/os-release`): `VMware Photon OS`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Looks like there is a problem when mounting a blob, where the incorrect credentials are being used. This looks like it was introduced when the transport reuse was added to the code.

**Comment by vikundral** [comment]
with any version ( tried with 26,27,29) of imgpkg greater than v0.25.0 I am hitting the below issue, seems like same behaviour for which above issue is opened. 

imgpkg copy --tar /root/foo/bar_latest.tar --to-repo abc-harbor.com/projecttest/testdeploy/tcx/foo-bar-custom --registry-username='testuser' --registry-password='testpass'
copy | importing 3 images...

0 B / 773.52 MiB [_______________________________________________________________________________________________] 0.00% ? p/s
copy | 
copy | done uploading images

Error uploading images: POST https://abc-harbor.com/projecttest/testdeploy/tcx/foo-bar-custom/blobs/uploads/?from=tcx%2Fsnapshot%2Ftanzu%2Ffoo0bar&mount=sha256%3Ae16be837292214ac682c9127e1c7ac894913c66dd1ae2d9c8955ab2c8c6c75a5: UNAUTHORIZED: unauthorized to access repository: tcx/snapshot/tanzu/foo-bar, action: pull: unauthorized to access repository: tcx/snapshot/tanzu/foo-bar, action: pull

**Comment by joaopapereira** [comment]
Hey, @vikundral thanks for opening this issue.

Was the tar created from that same registry? Because one of the checks that we do is to see if the images are in the same registry.
