### ISSUE TITLE
`--registry-insecure` broken for push and pull since v0.26.0 

### ISSUE THREAD

**Issue by ChristianCiach** [carvel-dev/imgpkg#378]
**What steps did you take:**
Starting with imgpkg v0.26.0 the option `--registry-insecure` has no effect for `push` and `pull` commands.

**What happened:**
```
$ imgpkg push --registry-insecure -i energy80.workstations.ems:5000/test:bundle -f test.bin
file: test.bin

imgpkg: Error: Writing 'energy80.workstations.ems:5000/test:bundle':
  Error while preparing a transport to talk with the registry:
    Unable to create round tripper:
      Get "https://energy80.workstations.ems:5000/v2/": http: server gave HTTP response to HTTPS client
```

**What did you expect:**
```
$ imgpkg push --registry-insecure -i energy80.workstations.ems:5000/test:bundle -f test.bin
file: test.bin
Pushed 'energy80.workstations.ems:5000/test@sha256:aeab02abc8ce72464a829decf4e4f98d3b0fe24901ed804a6bfd3022f74a486a'
Succeeded
```

**Environment:**

- imgpkg version (use `imgpkg --version`): imgpkg version 0.28.0
- Docker registry used (e.g. `Docker HUB`): Locally hosted `registry:2`
- OS (e.g. from `/etc/os-release`): Fedora Linux 35 (Workstation Edition)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by ChristianCiach** [comment]
Probably related to https://github.com/vmware-tanzu/carvel-imgpkg/pull/334

**Comment by joaopapereira** [comment]
After some investigation we made a fix for this issue
