### ISSUE TITLE
Show what happens between "done" and "Succeeded"

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/imgpkg#399]
**Describe the problem/challenge you have**
This is a very minor UX problem, but it's funny that imgpkg says "done" and then continues to run for a while before it says "Succeeded". 

Example: 
```
copy |
copy | done uploading images


[... this occupies a surprising amount of time, maybe ~15-30 seconds?]


Succeeded
```

**Describe the solution you'd like**

I may be naive but when it says "done" i didn't expect it to still be running afterwards. 

maybe something like the existing "done uploading" line followed by "and now here's what i'm doing next"

**Anything else you would like to add:**

This is not important, just capturing it as I was using imgpkg and surprised a little.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
That is a great question.
Between these 2 messages images does in fact tag all the images that need tagging, so it might take some time.

Maybe we can add a message informing the users that imgpkg is tagging images
