### ISSUE TITLE
drop spec in ImagesLock configuration

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#40]
**Describe the problem/challenge you have**

we typically have not included `spec` in various configuration resources in carvel. it feels a bit less consistent with other resources. i think we should drop it.

**Comment by joaopapereira** [comment]
This sounds like a plan.

**Comment by cppforlife** [comment]
fixed as part of #48

**Comment by gcheadle-vmware** [comment]
Closing issue with release of version 0.3.0
