### ISSUE TITLE
imgpkg v0.22.0 copy to docker registry Error uploading images

### ISSUE THREAD

**Issue by tiger1019** [carvel-dev/imgpkg#422]
**What steps did you take:**
1. docker  login registry.local
2.imgpkg copy   --tar tap-packages-1.2.0.tar   --to-repo registry.local/tanzu-application-platform/tap-packages 

**What happened:**
6.86 GiB / 6.87 GiB [================================================================================================================================================================================================================================]  99.91% 190.30 MiB/sError uploading images: PUT https://registry.local/v2/tanzu-application-platform/tap-packages/manifests/sha256-8730d4c869056068737aefa32983534cafecfcaa37c3cbcaff59c38b2d449358.imgpkg: multiple errors returned: UNKNOWN: unknown error; UNKNOWN: unknown error; map[]; MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:3a78847ea829208edc2d7b320b7e602b9d12e47689499d5180a9cc7790dec4d7

 6.87 GiB / 6.87 GiB [================================================================================================================================================================================================================================] 100.00% 172.79 MiB/sError uploading images: PUT https://registry.local/v2/tanzu-application-platform/tap-packages/manifests/sha256-369dea344c63e7c82d5565e41ccc58230508578fe105bb0ba55fd91dcbead0ac.imgpkg: multiple errors returned: UNKNOWN: unknown error; UNKNOWN: unknown error; map[]; MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:3a78847ea829208edc2d7b320b7e602b9d12e47689499d5180a9cc7790dec4d7

 6.87 GiB / 6.87 GiB [================================================================================================================================================================================================================================] 100.00% 158.37 MiB/sError uploading images: PUT https://registry.local/v2/tanzu-application-platform/tap-packages/manifests/sha256-8730d4c869056068737aefa32983534cafecfcaa37c3cbcaff59c38b2d449358.imgpkg: multiple errors returned: UNKNOWN: unknown error; UNKNOWN: unknown error; map[]; MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:3a78847ea829208edc2d7b320b7e602b9d12e47689499d5180a9cc7790dec4d7

 6.87 GiB / 6.87 GiB [================================================================================================================================================================================================================================] 100.00% 145.75 MiB/sError uploading images: PUT https://registry.local/v2/tanzu-application-platform/tap-packages/manifests/sha256-8730d4c869056068737aefa32983534cafecfcaa37c3cbcaff59c38b2d449358.imgpkg: multiple errors returned: UNKNOWN: unknown error; UNKNOWN: unknown error; map[]; MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:3a78847ea829208edc2d7b320b7e602b9d12e47689499d5180a9cc7790dec4d7

 6.87 GiB / 6.87 GiB [================================================================================================================================================================================================================================] 100.00% 135.29 MiB/sError uploading images: PUT https://registry.local/v2/tanzu-application-platform/tap-packages/manifests/sha256-8730d4c869056068737aefa32983534cafecfcaa37c3cbcaff59c38b2d449358.imgpkg: multiple errors returned: UNKNOWN: unknown error; UNKNOWN: unknown error; map[]; MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:3a78847ea829208edc2d7b320b7e602b9d12e47689499d5180a9cc7790dec4d7

 6.87 GiB / 6.87 GiB [============================================================================================================================================================================================================================] 100.00% 132.74 MiB/s 52s

copy | done uploading images

imgpkg: Error: Retried 5 times:
  PUT https://registry.local/v2/tanzu-application-platform/tap-packages/manifests/sha256-8730d4c869056068737aefa32983534cafecfcaa37c3cbcaff59c38b2d449358.imgpkg: multiple errors returned:
    UNKNOWN: unknown error; UNKNOWN: unknown error; map[]; MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:3a78847ea829208edc2d7b320b7e602b9d12e47689499d5180a9cc7790dec4d7

**What did you expect:**
imgpkg copy successful.

**Anything else you would like to add:**
it works fine with imgpkg  0.22.0

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.22.0
- Docker registry used (e.g. `Docker HUB`): docker-registry
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS or rhel8

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Hello @tiger1019 
A follow up does this work with version 0.22.0 or not? I do not fully understand your bug. If it is failing with a different version can you let us know what version that is?

Is it possible that when you created the tar you did not use the `--include-non-distributable-layers` and the missing layers are the non distributable layers?

Also not sure what registry you are using, but is it possible that you are running into this know issue with the `registry:2` registry? https://carvel.dev/imgpkg/docs/v0.29.0/faq-generic/#using-registry2-and-non-distributable-layer

**Comment by tiger1019** [comment]
Hellp @joaopapereira 
Thank you for your response, I am using registry:2 and the solution you provided has solved my problem.

**Comment by joaopapereira** [comment]
Going to close this issue, feel free to open if this problem happens again.
