### ISSUE TITLE
imgpkg copy fails when copying images to dockerhub

### ISSUE THREAD

**Issue by tanzu-tap** [carvel-dev/imgpkg#429]
**What steps did you take:**
[I am installing vmware tanzu application platform and when i got to the step to relocate the image registry to dockerhub it keeps failing even though I tried many times with correct credentials.]
Here is my command: 
imgpkg copy -b registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.1.0 --to-repo index.docker.io/mytap/tap-packages

**What happened:**
[imgpkg: Error: Non-retryable error:
  POST https://index.docker.io/v2/mytap/tap-packages/blobs/uploads/:
    UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:mytap/tap-packages Type:repository] map[Action:push Class: Name:mytap/tap-packages Type:repository]]t]

**What did you expect:**
[image copied succeful]

**Anything else you would like to add:**
[I have installed several version of imgpkg but that did not help . I also set env export IMGPKG_ENABLE_IAAS_AUTH=false still no success.]

**Environment:**

- imgpkg version (`imgpkg version 0.22.0`):
- Docker registry used ( `Docker HUB`): 
- OS (e.g. from `/etc/os-release`):  Ubuntu 20.04.4 LTS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Hey @tanzu-tap do you mind giving a try with a newer version to see if the problem was resolved?

I know that in some cases ubuntu was storing the docker configuration in a different location that was not being picked up correctly but that was solved in newer versions of go-containerregistry(library that we use to talk with the registry)

**Comment by tanzu-tap** [comment]
Hi @joaopapereira I tried several other versions but no luck. i even tried to use Mac but got same error

**Comment by joaopapereira** [comment]
Hey 😄 
Let's see if we can do some debugging. (If you prefer a more interactive back and forth you can jump into Kubernetes slack and we can talk there)


1. Does your user have access to push images to the repository `index.docker.io/mytap/tap-packages`?
1. Are you trying to run this command in a local machine or inside an IAAS?
1. Did you do `docker login` before you executed the command and still got the same error?
1. Following [this example](https://carvel.dev/imgpkg/docs/v0.31.0/auth/#via-environment-variables), if you set your credentials in the environment variables and retry to do the `imgpkg` command do you still get the same error?

**Comment by tanzu-tap** [comment]
1. Does your user have access to push images to the repository index.docker.io/mytap/tap-packages? Yes
2. Are you trying to run this command in a local machine or inside an IAAS? Bastion
3. Did you do docker login before you executed the command and still got the same error? Yes. I did docker login
4. Following [this example](https://carvel.dev/imgpkg/docs/v0.31.0/auth/#via-environment-variables), if you set your credentials in the environment variables and retry to do the imgpkg command do you still get the same error? Yes . I got same error.
Please What channel on Kubernetes slack can i talk to you? 
Thanks

**Comment by joaopapereira** [comment]
This is the channel where Carvel folks hang out https://kubernetes.slack.com/archives/CH8KCCKA5

**Comment by tanzu-tap** [comment]
coming with you now . thanks

**Comment by tanzu-tap** [comment]
imgpkg was able to copy the images after pushing. to the dockerhub account manually
