### ISSUE TITLE
Strange Error When Args are Passed to imgpkg Commands

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/imgpkg#44]
**What steps did you take:**

When running `imgpkg pull foo -o /tmp`, you will get the following error message:

```
Error: command 'foo' does not accept extra arguments 'imgpkg pull'
```

This also happens with `imgpkg push foo` and `imgpkg copy foo`:

```
Error: command 'foo' does not accept extra arguments 'imgpkg push'
```

```
Error: command 'foo' does not accept extra arguments 'imgpkg copy'
```

**What did you expect:**

An error stating that no arguments are accepted by these commands. Maybe also what options are necessary to use each command. 

**Anything else you would like to add:**

The above error is from Cobra, but perhaps it makes sense to add our own validation/error with something like the following with `imgpkg push`. This could be added to the command itself. An issue with this is that `imgpkg` traditionally has its error messages displayed in red text, but the error comes out with no color.

```go
PreRunE: func(cmd *cobra.Command, args []string) error {
	if len(args) > 0 {
            return fmt.Errorf("command 'imgpkg %s' accepts no args and requires the '--image' or '--bundle' with '--file' option", cmd.Name())
	}
	    return nil
	}
}
```

**Comment by cppforlife** [comment]
this error comes from shared library between our tools: https://github.com/vmware-tanzu/carvel-imgpkg/blob/develop/pkg/imgpkg/cmd/imgpkg.go#L54

**Comment by danielhelfand** [comment]
Thanks for pointing out. Seeing the helper function [here](https://github.com/vmware-tanzu/carvel-imgpkg/blob/d4982fa6c0aa2ef64e4151e39b91785e437610bf/vendor/github.com/cppforlife/cobrautil/misc.go#L52) where the error originates.
