### ISSUE TITLE
Add the ability to check if a remote artifact is a bundle

### ISSUE THREAD

**Issue by itaytalmi** [carvel-dev/imgpkg#446]
**Describe the problem/challenge you have**
[A description of the current challenge that you are experiencing.]

Following another issue I've opened in upstream Tanzu Framework:
https://github.com/vmware-tanzu/tanzu-framework/issues/3757

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX (ex: new CLI argument name, the behavior expected).]

In that case, a specific bundle couldn't be pulled using `imgpkg copy` because [this script](https://github.com/vmware-tanzu/tanzu-framework/blob/main/hack/gen-publish-images-totar.sh#L113) had incorrectly attempted to use `imgpkg copy -i` rather than `imgpkg copy -b`. Also, currently, as you can see, the script has some hardcoded values for specific bundles, as it doesn't know which artifacts are bundles and which artifacts are images.

I think it would be great to have the ability to "inspect" a remote artifact to determine whether it's a bundle or not. This would allow for a dynamic pre-check in such cases.

Using Docker or Crane CLI, I've managed to get this information.

For example:

Output of `docker inspect projects.registry.vmware.com/tkg/packages/capabilities:v0.25.0-23-g6288c751_vmware.1`:

```text
...
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dev.carvel.imgpkg.bundle": "true" # This is the label imgpkg should be able to extract
            }
        },
...
```

Output of `crane config projects.registry.vmware.com/tkg/packages/capabilities:v0.25.0-23-g6288c751_vmware.1`:

```text
{"architecture":"","created":"0001-01-01T00:00:00Z","history":[{"author":"imgpkg","created":"0001-01-01T00:00:00Z","created_by":"imgpkg"}],"os":"","rootfs":{"type":"layers","diff_ids":["sha256:1390449d75a402107fd54acb217a4941ef5175da7725026ad5abe625e7befc84"]},
"config":{"Labels":{"dev.carvel.imgpkg.bundle":"true"}}}
```

The last part of that output also contains this info.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

See above.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
Hello @itaytalmi 
imgpkg does have a command that describes the contents of a bundle.
in your example:
```
$ imgpkg describe -b projects.registry.vmware.com/tkg/packages/capabilities:v0.25.0-23-g6288c751_vmware.1
Bundle SHA: sha256:03d22253164c1aabbd3527a4287ef18808466b26346d79ade57238d66e2ed468

Images:
  - Image: projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager@sha256:4a91b04faa30f7b6e0dd41f50e231aaba829381354d9bb430ddda8354ee4c1df
    Type: Image
    Origin: projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager@sha256:4a91b04faa30f7b6e0dd41f50e231aaba829381354d9bb430ddda8354ee4c1df
    Annotations:
      kbld.carvel.dev/id: capabilities-controller-manager:latest
      kbld.carvel.dev/origins: - resolved:
          tag: v0.25.0-23-g6288c751
          url: projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager:v0.25.0-23-g6288c751


Succeeded
```


The only caveat with this is if you try to run describe on an image you will get the following error:
```
$ imgpkg describe -b projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager@sha256:4a91b04faa30f7b6e0dd41f50e231aaba829381354d9bb430ddda8354ee4c1df
imgpkg: Error: Only bundles can be described, and projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager@sha256:4a91b04faa30f7b6e0dd41f50e231aaba829381354d9bb430ddda8354ee4c1df is not a bundle
```

Do you think this behavior is enough to get what you need?

**Comment by itaytalmi** [comment]
Thank you @joaopapereira, I'm familiar with the `imgpkg describe` but I think that is not ideal, because you still need to know it's a bundle to run `imgpkg describe -b`, otherwise it results in an error.
What I want to do is check whether the artifact is a bundle by the `{"dev.carvel.imgpkg.bundle":"true"}` label, for example. Does imgpkg have any output containing the labels (like Docker/Crane)? If so, maybe it could be parsed.

**Comment by joaopapereira** [comment]
No, that functionality does not exist.

`imgpkg` tries to be very precise about the operation that is executing. So there is an expectation that when a user calls `imgpkg`, it knows what they want to copy/pull.

**Comment by vrabbi** [comment]
the other issue with describe is that it can be a long running command if the bundle is large and has many nested bundles making it not an optimal choice. 
it would be nice if like we have the "tag ls" command in imgpkg, if we also had a "inspect", or "labels ls" command that could return data on a specific oci artifact.

**Comment by jayunit100** [comment]
ah .  ok.  some kinda imgpkg support would be good here, any equivalent ideas we could implement @joaopapereira ?

**Comment by joaopapereira** [comment]
from offline discussions we had, looks like tanzu-framework is reworking that script which should solve your original problem.

> it would be nice if like we have the "tag ls" command in imgpkg, if we also had a "inspect", or "labels ls" command that could return data on a specific oci artifact.

@vrabbi What kind of information you are thinking about? Do you have an use case for it apart from the original one in this issue?

**Comment by vrabbi** [comment]
Another use case is images built with buildpacks have labels added to them with a bunch of information that could br very beneficial for people to know such as what buildpacks were used, sbom information and so on. As this is metadata on an image, it would be nice to be able to use imgpkg to view the labels on the images so as to have a simple way of detecting what an kmage contains

**Comment by itaytalmi** [comment]
@joaopapereira Additionally, the original issue wasn't solved - Tanzu Framework hardcodes imgpkg bundle names in that script, which is the reason we ran into this issue in the first place. If we could inspect the image/bundle using imgpkg before pulling it, we could have a much more dynamic and generic approach and it wouldn't be necessary to hardcode any bundle names anywhere. It makes a lot of sense in my opinion.

**Comment by vrabbi** [comment]
@itaytalmi the issue is being solved via a new command in tanzu cli that will make this script irrelevant in the future. PRs are already starting to show up in framework for it.

**Comment by joaopapereira** [comment]
@itaytalmi I was talking about https://github.com/vmware-tanzu/tanzu-framework/pull/3743

**Comment by joaopapereira** [comment]
Is it ok if we close this issue since it looks like there will be a solution in tanzu-framework for this particular problem?

**Comment by itaytalmi** [comment]
Yes. Thanks.
