### ISSUE TITLE
Support OCI image layout

### ISSUE THREAD

**Issue by imurata** [carvel-dev/imgpkg#448]
**Describe the problem/challenge you have**
I am trying to push a full stack of [buildpacks](https://github.com/paketo-buildpacks/bionic-full-stack), but it is registered as a file instead of as oci image.

**Describe the solution you'd like**
[crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md) supports oci image layout.
```
tar xf build.oci
cd build
crane push . myharbor.lab/library/build-image
```
So, I want to push the image of oci layout with imgpkg command as crane.
```
tar xf build.oci
cd build
imgpkg push -i myharbor.lab/library/build-image -f .
```
 

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.

**Comment by joaopapereira** [comment]
Sorry I dropped the ball on this issue and forgot to answer to it.

Just to be clear here the steps you are doing are:
1. Create an OCI Image
2. Save that image to a tar in disk
3. Want to copy it to a registry

Is this correct?

If so I believe that in some sense this could be achieved by using the `copy` command instead. The only caveat right now is that imgpkg does not support copying tars to a registry that are not in an `imgpkg format`.
Maybe adding this functionality is something that indeed is interesting.
