### ISSUE TITLE
Support Remote Files with --file Option for imgpkg push

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/imgpkg#49]
**Describe the problem/challenge you have**

For users managing manifests in a different repository than their main projects, there is no way with `imgpkg push -f` to reference folders or files via a url. 

**Describe the solution you'd like**

Support pushing folders/files via a url with `imgpkg push -f` like below:

```
imgpkg push -f https://raw.githubusercontent.com/vmware-tanzu/carvel-imgpkg/9ecde093d13a203f9cbf844ede5951aa8d489c97/examples/basic-step-1/config.yml -i user/repo
```

**Anything else you would like to add:**

This could also assist with educating users about `imgpkg` when they go through the `imgpkg` workflow docs. Being able to reference remote files as opposed to needing to pull down examples while going through the workflow would be helpful for users just getting started.

**Comment by cppforlife** [comment]
> Support pushing folders/files

what would a folder support look like? im not sure single file use case is that common.

im not too hot about this feature since fetching functionality arguably should be in a different tool like vendir, but ive done something similar before in kapp/ytt (hard to tell if its ultimately worth the price though).

**Comment by iamhsk** [comment]
At this point we don't see a strong use case for this issue so moving back to `carvel-triage`. If we find a use case in the future, we can change it back to `carvel-accepted`.

**Comment by danielhelfand** [comment]
I think we should just close it then and wait for someone to ask for this as a use case in a new issue. That can be a better way to determine if it's useful or not. 

I think we probably should not mark something as `carvel-triage` that has already been triaged or accepted. We should just say the issue is not prioritized at the moment or close it.

**Comment by joaopapereira** [comment]
@danielhelfand I think your comment makes sense. So after talking with @iamhsk we decided to close this issue for now.

Feel free to reopen this issue in case a strong use case has come to light.
