### ISSUE TITLE
Keep tag when copying an Image

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#54]
**Describe the problem/challenge you have**
Currently, `imgpkg` can retain information about the tag of a bundle but when we try to use it with an image it does not retain it.

**Describe the solution you'd like**

The scenario of copying an image
**Given** a set of files in examples/basic-step-1
**And** create an image in the registry by executing `imgpkg push -i localhost:5000/some-image:v0.5.0 -f examples/basic-step-1`
**When** copying the image to a different repository by executing `imgpkg copy -i localhost:5000/some-image:v0.5.0 --to-repo localhost:5000/some-other-image`
**Then** I can execute `docker pull localhost:5000/some-other-image:v0.5.0`
**And** will be able to retrieve the image created in the first step

Based on a request from Zihan Jiang: [Slack conversations](https://kubernetes.slack.com/archives/CH8KCCKA5/p1610484485443500)

**Comment by gcheadle-vmware** [comment]
Thanks @joaopapereira, 

Currently prioritizing this work.

**Comment by joaopapereira** [comment]
Released in version 0.8.0
