### ISSUE TITLE
Copying a bundle with the `image-is-bundle-check` being false doesn't work as expected.

### ISSUE THREAD

**Issue by praveenrewar** [carvel-dev/imgpkg#544]
**What steps did you take:**

```bash
 ## Case 1
 $ imgpkg pull -b this-is-a-bundle-for-sure
 
 ## Case 2
 $ imgpkg pull -b this-is-a-bundle-for-sure --image-is-bundle-check=false
```

When we run the above 2 commands, the expectation would be to have the same result, but right now because of [this](https://github.com/carvel-dev/imgpkg/blob/1a02bc4ced5e9b0d1cd13ae080a1f830ef8a4ee8/pkg/imgpkg/cmd/pull.go#L84) and [this](https://github.com/carvel-dev/imgpkg/blob/1a02bc4ced5e9b0d1cd13ae080a1f830ef8a4ee8/pkg/imgpkg/v1/pull.go#L105), in the second scenario we will pull it as an image, which might be a bit weird because we are trying to pull a bundle using the bundle flag.

**Anything else you would like to add:**
The value of the flag `image-is-bundle-check` shouldn't effect copying a bundle or we shouldn't allow using the flag itself.

**Environment:**

- imgpkg version (use `imgpkg --version`):
- Docker registry used (e.g. `Docker HUB`): 
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Hey
I think we should not allow this flag to be used with `-b`. It should throw an error pointing the user to use the `-i` flag.
