### ISSUE TITLE
Case when the registry link for pull is a image but the flags are -I along with —image-is-bundle-check flag=true which results in the image being pulled. 

### ISSUE THREAD

**Issue by ashpect** [carvel-dev/imgpkg#559]
**What steps did you take:**
Pls see #544 for context.
During my attempt to fix #544 and my analysis of all the cases and the flow of code with the flags.
<img width="1112" alt="Screenshot 2023-08-11 at 2 11 45 PM" src="https://github.com/carvel-dev/imgpkg/assets/93992470/424b807e-3c8d-4949-a3bd-e18f862bd97e">
I have opened a PR with a suggestive fix.

**What happened:**
It seems like the case when the link it image but the flags are -I along with —image-is-bundle-check flag=true results in the image being pulled. 

**What did you expect:**
An error when I pass the wrong flag with link of an image.

**Environment:**

- imgpkg version (0.37.3):
- Docker registry used (Docker HUB): 
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
Hey @ashpect, I think there is a some confusion around the `image-is-bundle-check` flag. The flag description says:
```bash
--image-is-bundle-check                       Error when image is a bundle (disable pulling bundles via -i) (default true)
```
So the expectation is 
* when `-b` is being used, then usage of this flag shouldn't be allowed as it's only meant to be used when `-i` us set (we can add it to the [validations](https://github.com/carvel-dev/imgpkg/blob/1a02bc4ced5e9b0d1cd13ae080a1f830ef8a4ee8/pkg/imgpkg/cmd/pull.go#L108)). This is issue #544.
* when `-i` is used and we are trying to pull something that is actually a bundle, then
     * we should error out if the flag is set to _true_, which should be working as expected.
     * we should pull the bundle as an image if the flag is set to _false_, which should be working as expected.
* when `-i` is used and we are trying to pull something that is actually an image, then the value of this flag shouldn't matter which should also be working as expected.

**Comment by ashpect** [comment]
Thanks for the input. I'll change the fix accordingly.
I have closed the [original pr](https://github.com/carvel-dev/imgpkg/pull/560) for both issues and fixed #544 [here](https://github.com/carvel-dev/imgpkg/pull/563)

However, regarding this current opened issue :
"when -i is used and we are trying to pull something that is actually an image, then the value of this flag shouldn't matter which should also be working as expected."  : Agreed but if someone sets the flag to true (manually) can be a bit confusing in this case, since it's an image ( as checked by code) ; so shouldn't we error saying that what you are pulling is an image, don't use this flag , or maybe at least a warning stating that we pulled the image , but the don't use this flag. ?

**Comment by praveenrewar** [comment]
The flag `--image-is-bundle-check` is basically asking imgpkg to check if the image that we are trying to pull is a bundle and through an error if it's a bundle, but if it is an image then pull the image. So, if what we are trying to pull is an image, then we would want to pull the image irrespective of the value of `--image-is-bundle-check` (the check will be performed, but won't through an error because it's an image).

**Comment by ashpect** [comment]
Hmm..thanks, understood. I was just hung up on the fact that the user might use flag with true confusing himself. But understood that the flag is not meant for setting as false, its default being true.

**Comment by praveenrewar** [comment]
Closing this issue, but let me know if you have any other questions.
