### ISSUE TITLE
e2e tests are messing with global docker config.json

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#57]
this is surprising as a user of e2e tests since changes to .docker/config.json affects my other operations on the computer. can we find an alternative way of testing whatever needs to be tested?

**Comment by danielhelfand** [comment]
The test in question is [here](https://github.com/vmware-tanzu/carvel-imgpkg/blob/9d74a8c43e62219757ace4bbde7f5324e60bee75/test/e2e/copy_test.go#L25). Part of the challenge of this feature was how to mock a race condition with gcr that occurs when a gcloud token is expired.

The test alters config.json to shell out to a [script](https://github.com/vmware-tanzu/carvel-imgpkg/blob/9d74a8c43e62219757ace4bbde7f5324e60bee75/test/e2e/assets/docker-credential-gcloud-race-condition-db-error) that produces a mock race condition in a container. 

The test basically makes sure the retry logic added as part of the work (#33) that added this test is able to recover from the initial failure.

**Comment by cppforlife** [comment]
> The test basically makes sure the retry logic added as part of the work (#33) that added this test is able to recover from the initial failure.

briefly looking at code for #33, i see that we added retry logic for this error into NewImageRefDescriptors. from what i can see the retry logic is pretty specific to way of interacting with the registry. i would recommend exploring writing a RetryableRegistry impl for Registry interface that knows how to retry on gcloud error. you can then test that class in isolation at a lower level than e2e.
