### ISSUE TITLE
Is there any way to disable progress bar shown during pushing of images ?

### ISSUE THREAD

**Issue by tarun818** [carvel-dev/imgpkg#666]
I am using below snippet in my code base to push images 

`// Create a CopyOptions object for imgpkg's copyOptions.Run()
copyOptions := imgpkg.NewCopyOptions(goUi.NewConfUI(goUi.NewNoopLogger()))
//...
//...
// Set fields according to parameters and default imgpkg configurations, as well as registry auth
copyOptions.RepoDst = <some repo>
copyOptions.Concurrency = 1
//... and so on and finally, I call Run as shown below

copyOptions.Run() 
`
This copyOptions.Run() will start a progress bar as shown [here](https://github.com/carvel-dev/imgpkg/blob/f99dae6c97fe77622a6190bcbfbdbb75cb4cd401/pkg/imgpkg/cmd/copy.go#L108) 

I want to disable it. is this possible ?

**Comment by praveenrewar** [comment]
@tarun818 I don't think there's a way to disable the progress bar while using the `Run` function. Unfortunately we don't have apis for the copy command yet which would have been helpful here.

cc @joaopapereira

**Comment by joaopapereira** [comment]
Hey
I am currently working on extracting the API for copy. Unfortunately, I do not have a lot of bandwidth to do it. When we extract it, it would be easier for you to call imgpkg.

**Comment by tarun818** [comment]
@joaopapereira Thanks for your response.
If possible, can you share a tentative timeline for when we can expect this change?

**Comment by joaopapereira** [comment]
I created a PR that will add the v1 API for copy https://github.com/carvel-dev/imgpkg/pull/668. There is another PR that is being reviewed that does change the code in copy and we need to decide if we want to merge this first and add rebase that PR or the reverse.

**Comment by praveenrewar** [comment]
The PR is merged. @tarun818 Could you give the copy apis a try now (we haven't made a release yet but you should be able to use the latest commit sha).
