### ISSUE TITLE
imgpkg copy from lock file does not copy annotations

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/imgpkg#77]
**What steps did you take:**

```
kbld -f examples/simple-app-build-and-push/ --imgpkg-lock-output foo.yml
imgpkg copy --lock foo.yml --lock-output foo2.yml --to-repo localhost:5000/foo
```

```foo.yml
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: simple-app
  image: localhost:5000/cppforlife/kbld-simple-app2@sha256:09f45eea0d452749445d1d015745b2bc5cfcbfb49f952d482d14f37ae7680a38
kind: ImagesLock
```

```foo2.yml
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- image: localhost:5000/foo@sha256:09f45eea0d452749445d1d015745b2bc5cfcbfb49f952d482d14f37ae7680a38
kind: ImagesLock
```

**What happened:**
The `annotations` were dropped when I copied the image

**What did you expect:**
They'd be maintained, so that the mappings of app -> image would be maintained

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.3.0

**Comment by joaopapereira** [comment]
I was able to reproduce the issue.

The main problem here is that usually the lock file is saved with the bundle, but in this case, no bundle was created so we need to make sure that the output lock file contains the annotations that were present in the initial images lock file.

---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.
