### ISSUE TITLE
Document Use of the BundleLock File Under the imgpkg Workflow Docs

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/imgpkg#79]
In reviewing the [workflow documentation](https://carvel.dev/imgpkg/docs/latest/basic-workflow/) for imgpkg, there is currently no mention of using a BundleLock in the workflows. 

It would be helpful to document when someone should make use of a BundleLock file and try and find a way to incorporate it into the workflow docs. While the current [documentation on the concept of the BundleLock](https://carvel.dev/imgpkg/docs/latest/resources/#bundlelock-configuration) is clear, it is not entirely clear when one should be used. 

---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.

**Comment by danielhelfand** [comment]
It does seem there are some docs on it under command docs, but they are difficult to locate. Might make sense to directly involve in workflows still and also link to command docs below from where BundleLock is defined under resources.

https://carvel.dev/imgpkg/docs/latest/commands/#generating-a-bundlelock
https://carvel.dev/imgpkg/docs/latest/commands/#pulling-via-lock-file
https://carvel.dev/imgpkg/docs/latest/commands/#copying-via-lock-file

**Comment by joaopapereira** [comment]
I think we are not showcasing this feature, but it is nice to have it especially if you are doing some sort of automation. Adding maybe a scenario of some sort of automation on the documentation could make it easier to understand the purpose.

**Comment by danielhelfand** [comment]
It may even be simple enough to link to the command docs on the topic from where the BundleLock definition is documented. Just something to help connect all the pieces of it maybe is enough for now.
