### ISSUE TITLE
Document Recursive Bundle feature

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#88]
## Use Case

**As A** Software Packager
**I want to** Create a bundle to distribute the multiple applications that are part of a deployment
**So that** Application consumers can retrieve all needed software from a single place

### Scenario 1: Recursive bundle documentation
**Given** I access https://carvel.dev/imgpkg
**When** Visit the documentation page
**Then** I can see documentation about the new feature

**Notes**
- We can piggyback on the proposal https://github.com/k14s/design-docs/blob/002-recursive-bundles/imgpkg/002-recursive-bundles/README.md
- We should explain well the pull command to inform the reader where the bundles will be placed on the disk

**Comment by aaronshurley** [comment]
Completed with this PR being merged: https://github.com/vmware-tanzu/carvel.dev/pull/81
