### ISSUE TITLE
carry over kbld improvements

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/imgpkg#9]
- [x] use same transport object to avoid too many fds
- [x] https://github.com/k14s/kbld/issues/46
- [x] https://github.com/k14s/kbld/issues/44
- [x] https://github.com/k14s/kbld/commit/dc40e8951749bedfed3891b39ad022976316e1f8
- [ ] others?

**Comment by ewrenn8** [comment]
Should bring this over as well:
- [x] [Reusing transport because of too many open fds](https://github.com/k14s/kbld/commit/b7f04861f336fb9f32d676cebea98c1afc23288c)

**Comment by StevenLocke** [comment]
Brought the 4 improvements in, and all merged to develop!
