### ISSUE TITLE
Retain executable flag on files in bundle

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/imgpkg#93]
**Describe the problem/challenge you have**
Right now when you do an `imgpkg push` to create a bundle it will drop the executable flag on any files, it is hard-coded to create every file in the tarball with 0600: https://github.com/vmware-tanzu/carvel-imgpkg/blob/499b334d53c78a9624f427e96dcb6e1a87dd6d50/pkg/imgpkg/image/tar_image.go#L129

**Describe the solution you'd like**
The executable flag should be kept on the files

**Anything else you would like to add:**
Slack thread: https://kubernetes.slack.com/archives/CH8KCCKA5/p1614181788053900

**Comment by joaopapereira** [comment]
Looks good to me.

We should ensure the following:
- Only add execution permission to files that had execution permission previously

---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.

**Comment by aaronshurley** [comment]
When you pick up this story, discuss the possibility of keeping the ownership bits.

**Comment by joaopapereira** [comment]
Shipped with version 0.7.0
